### PR TITLE
Deefault test fix

### PR DESCRIPTION
**Pull request by saltastroops**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/36)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/36)* status: all files reviewed, 5 unresolved discussions (waiting on @saltastroops)

___
*[frontend/src/app/mock/service/mock-proposal.service.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-Mc9zk4i0APQIkvulPFh:-Mc9zk4j3Ue7oE8xMYcw:b-opl6yk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bedbe0341739861d96065108978f001b43861388/frontend/src/app/mock/service/mock-proposal.service.spec.ts#L1)):*
> ```XML
> import { TestBed } from '@angular/core/testing';
> ```

This test file probably is unnecessary.
___
*[frontend/src/app/proposal/proposal.component.spec.ts, line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-McA-23BDAQ8pJLLW_0E:-McA-23BDAQ8pJLLW_0F:bt8shf1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/proposal/proposal.component.spec.ts#L24)):*
> ```XML
> 
>   it('should create', () => {
>     expect(true).toBeTruthy();
> ```

This test doesn't test anything...
___
*[frontend/src/app/proposal/proposal-details/proposal-details.component.spec.ts, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-McA2apD62Ma5DR_wEG1:-McA2apD62Ma5DR_wEG2:b-ue3asb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/proposal/proposal-details/proposal-details.component.spec.ts#L8)):*
> ```XML
> 
> describe('ProposalDetailsComponent', () => {
>   const general_proposal_info = {
> ```

That is a lot of configuration for a test which doesn't test much... :-/
___
*[frontend/src/app/service/block.service.spec.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-McA2wuGAb1BjJrcQCS-:-McA2wuGAb1BjJrcQCS0:bucofh9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/service/block.service.spec.ts#L3)):*
> ```XML
> import { TestBed } from '@angular/core/testing';
> 
> import { BlockService } from './block.service';
> ```

This test file should be deleted -- BlockService is an interface really...
___
*[frontend/src/app/service/real/real-proposal.service.spec.ts, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-Mc9xfRKCL_8J0cDRs4S:-Mc9xfRLB0-qaYBv2cn-:bo57fzh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/service/real/real-proposal.service.spec.ts#L8)):*
> ```XML
> 
>   beforeEach(() => {
>     httpClientSpy = jasmine.createSpyObj('HttpClient', ['get']);
> ```

You should add two tests, I think:

1. The service emits whatever the HTTP request has returned (or whatever else it should emit instead)
2. The service emits an error when the HTTP request fails.\

See real-block.service.ts and real-block.service.spec.ts.

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/36)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/mock/service/mock-proposal.service.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-Mc9zk4i0APQIkvulPFh:-McDegBd0vfM7B4cleXz:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/bedbe0341739861d96065108978f001b43861388/frontend/src/app/mock/service/mock-proposal.service.spec.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test file probably is unnecessary.
</blockquote></details>

removed
___
*[frontend/src/app/service/block.service.spec.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-McA2wuGAb1BjJrcQCS-:-McDf_Yi0E8YO-obhpBy:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/service/block.service.spec.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This test file should be deleted -- BlockService is an interface really...
</blockquote></details>

removed
___
*[frontend/src/app/service/real/real-proposal.service.spec.ts, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-Mc9xfRKCL_8J0cDRs4S:-McE54PY3DMWpT5Y6aj-:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/service/real/real-proposal.service.spec.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should add two tests, I think:

1. The service emits whatever the HTTP request has returned (or whatever else it should emit instead)
2. The service emits an error when the HTTP request fails.\

See real-block.service.ts and real-block.service.spec.ts.
</blockquote></details>

done

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/36)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/proposal/proposal-details/proposal-details.component.spec.ts, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/36#-McA2apD62Ma5DR_wEG1:-McEEW083b7WQRzXxRrT:bb7f2mf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d195b0ac8ac4bf9c87c7aca5bdebd027d06a0f3c/frontend/src/app/proposal/proposal-details/proposal-details.component.spec.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That is a lot of configuration for a test which doesn't test much... :-/
</blockquote></details>

done

**Review by hettlage — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/36)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saltastroops)

**Pull request merged**
