### PR TITLE
Error logging

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/main.ts, line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhJ1PrN0UMyYRZfV0RE:-MhJ1PrP5tjWDXX3wHnw:b7880d2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2f3fb155c23c19ebd81bc27260588af14c7e7c/frontend/src/main.ts#L21)):*
> ```XML
>   // of transactions for performance monitoring.
>   // We recommend adjusting this value in production
>   tracesSampleRate: 1.0,
> ```

This should be defined in the environment file(s), and at least in production it should be less than 1.
___
*[frontend/src/environments/environment.ts, line 8 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhIxnq5-3E5KzgojGgQ:-MhIxnq5-3E5KzgojGgR:b-iz2l95) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2f3fb155c23c19ebd81bc27260588af14c7e7c/frontend/src/environments/environment.ts#L8)):*
> ```XML
>   apiUrl: 'http://127.0.0.1:8001',
>   production: false,
>   sentryDSN: 'https://f379121cdac147a1a1803567a1b6f126@o947730.ingest.sentry.io/5897019',
> ```

Should be replaced with an environment variable, as in main.ts.

In all fairness, this is no secret (I was wrong there yesterday) -- you use it in the browser after all. But still, it shouldn't be hardcoded in this file, not least because you might want to have different DSNs for development and production. See https://angular.io/guide/build on how to achieve this.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/main.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNntzrAXIcbpPCbkf4:-MhNntzrAXIcbpPCbkf5:b3yffo0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/main.ts#L9)):*
> ```XML
> import { environment } from './environments/environment';
> 
> Sentry.init({
> ```

You might consider logging a warning if no Sentry DSN has been set.
___
*[frontend/src/main.ts, line 21 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnGhU8QGlzh78zj1w:-MhNnGhU8QGlzh78zj1x:bkxurc6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/main.ts#L21)):*
> ```XML
>   // of transactions for performance monitoring.
>   // We recommend adjusting this value in production
>   tracesSampleRate: 1.0,
> ```

1.0 --> environment.sentryTracesSampleRate
___
*[frontend/src/app/app.module.ts, line 134 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNo_wa36RBNaL5IHYZ:-MhNo_wa36RBNaL5IHY_:b-8vvgye) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/app/app.module.ts#L134)):*
> ```XML
>     { provide: ErrorHandler,
>       useValue: Sentry.createErrorHandler(
>         {showDialog: true,
> ```

Is the dialog shown if no DSN is set? If so, showDialog should be set to false if no DSN is set.
___
*[frontend/src/environments/environment.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnSyA68UNyMFyWrxp:-MhNnSyA68UNyMFyWrxq:b-p4dy9p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.ts#L9)):*
> ```XML
>   production: false,
>   sentryDSN: '',
>   tracesSampleRate: 1.0,
> ```

tracesSampleRate ---> sentryTracesSampleRate
___
*[frontend/src/environments/environment.dev.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnZkhCMZj5c-r8aZ2:-MhNnZkhCMZj5c-r8aZ3:b-p4dy9p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.dev.ts#L5)):*
> ```XML
>   production: false,
>   sentryDSN: 'https://f379121cdac147a1a1803567a1b6f126@o947730.ingest.sentry.io/5897019',
>   tracesSampleRate: 1.0,
> ```

tracesSampleRate ---> sentryTracesSampleRate
___
*[frontend/src/environments/environment.prod.ts, line 4 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNmosj2VCUX8C307iD:-MhNmosj2VCUX8C307iE:bi4mdzv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L4)):*
> ```XML
>   apiUrl: '',
>   production: true,
>   sentryDSN: '',
> ```

Should be: 'https://dbf47d4bad1740b485b98cd87c35a0e6@o226051.ingest.sentry.io/5913441'
___
*[frontend/src/environments/environment.prod.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNmu4R6-waWz6yBMYi:-MhNmu4R6-waWz6yBMYj:b-id5xxy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L5)):*
> ```XML
>   production: true,
>   sentryDSN: '',
>   tracesSampleRate: 0.8,
> ```

Probably should be even lower. I guess tracing needs some investigation at some point. I'd suggest 0.1 for the time being.
___
*[frontend/src/environments/environment.prod.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnavECtc6wQOiL7fX:-MhNnavFDErcFtBWKF5k:b-p4dy9p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L5)):*
> ```XML
>   production: true,
>   sentryDSN: '',
>   tracesSampleRate: 0.8,
> ```

tracesSampleRate ---> sentryTracesSampleRate

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/main.ts, line 21 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhJ1PrN0UMyYRZfV0RE:-MhNnov60ttqc2RyaoDZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2f3fb155c23c19ebd81bc27260588af14c7e7c/frontend/src/main.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be defined in the environment file(s), and at least in production it should be less than 1.
</blockquote></details>

Done.
___
*[frontend/src/main.ts, line 21 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnGhU8QGlzh78zj1w:-MhNr2Gp7uzA0skm8vwr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/main.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

1.0 --> environment.sentryTracesSampleRate
</blockquote></details>

Done.
___
*[frontend/src/app/app.module.ts, line 134 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNo_wa36RBNaL5IHYZ:-MhNr3Zw9nZSbKeywPPb:b-dpg4ec) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/app/app.module.ts#L134)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is the dialog shown if no DSN is set? If so, showDialog should be set to false if no DSN is set.
</blockquote></details>

No, the dialog is not shown when the DSN is not set.
___
*[frontend/src/environments/environment.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnSyA68UNyMFyWrxp:-MhNqrFfCHcjgDZX-Hhq:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

tracesSampleRate ---> sentryTracesSampleRate
</blockquote></details>

Done.
___
*[frontend/src/environments/environment.dev.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnZkhCMZj5c-r8aZ2:-MhNqqPU2VGA4QjowpBw:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.dev.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

tracesSampleRate ---> sentryTracesSampleRate
</blockquote></details>

Done.
___
*[frontend/src/environments/environment.prod.ts, line 4 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNmosj2VCUX8C307iD:-MhNqozHD6YoXyLVpKTS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be: 'https://dbf47d4bad1740b485b98cd87c35a0e6@o226051.ingest.sentry.io/5913441'
</blockquote></details>

Done.
___
*[frontend/src/environments/environment.prod.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNnavECtc6wQOiL7fX:-MhNqnSC6dqBhqBGe4TA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

tracesSampleRate ---> sentryTracesSampleRate
</blockquote></details>

Done.
___
*[frontend/src/environments/environment.prod.ts, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNmu4R6-waWz6yBMYi:-MhNqnjX-8DvVB7QYF-q:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/environments/environment.prod.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably should be even lower. I guess tracing needs some investigation at some point. I'd suggest 0.1 for the time being.
</blockquote></details>

Done.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)* status: 4 of 8 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/main.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/76#-MhNntzrAXIcbpPCbkf4:-MhNxgaICMuPTiOrxoLn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9c20d2e0cc29411832d75d6b7c12c32e32362100/frontend/src/main.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider logging a warning if no Sentry DSN has been set.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
