### PR TITLE
Test database

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[python/pyproject.toml, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeef3BBg1pypAXMGFo:-MTeef3BBg1pypAXMGFp:b3lsq9m) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/pyproject.toml#L2)):*
> ```TOML
> [tool.poetry]
> name = "web-manager"
> ```

I'm not sure whether Poetry assumes the name to be the same as the code directory. I'd rather leave it as app.
___
*[python/pyproject.toml, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeepqNEun8SUEfxpDG:-MTeepqNEun8SUEfxpDH:b-ghnrg6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/pyproject.toml#L11)):*
> ```TOML
> fastapi = "^0.63.0"
> uvicorn = "^0.13.3"
> PyMySQL = "^1.0.2"
> ```

Might need discussion.
___
*[python/tests/create_test_database.py, line 39 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeicc-6JwZSZox6zN3:-MTeicc-6JwZSZox6zN4:b3n7kvj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/create_test_database.py#L39)):*
> ```Python
> 
>     MAIN_DB_HOST = main_db_host
>     MAIN_DB_USER = main_db_user
> ```

The uppercase variables are unnecessary.
___
*[python/tests/create_test_database.py, line 72 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeil9T7hHR_b6P-9vO:-MTeil9T7hHR_b6P-9vP:buoxax5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/create_test_database.py#L72)):*
> ```Python
>     os.system(f"rm {dump_file}")
> # ________________________________________End Create a dump SDB_________________________________________________________
> ```

These comments might suggest splitting up the function.
___
*[python/tests/sdb_sensitive.py, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefiVw7DL79gnDtNlm:-MTefiVw7DL79gnDtNln:bseri5r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L27)):*
> ```Python
>     with test_db_connection.cursor() as cur:
>         cur.execute("SELECT Investigator_Id FROM Investigator")
>         results = cur.fetchall()  # results are  type tuple of tuple
> ```

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
___
*[python/tests/sdb_sensitive.py, line 28 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefZGQA9C-9NsgrrQk:-MTefZGQA9C-9NsgrrQl:bq623e6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L28)):*
> ```Python
>         cur.execute("SELECT Investigator_Id FROM Investigator")
>         results = cur.fetchall()  # results are  type tuple of tuple
>         for investigator in results:
> ```

You could use list comprehension.
___
*[python/tests/sdb_sensitive.py, line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefvaH3AF0wFlQ_tVT:-MTefvaH3AF0wFlQ_tVU:bseri5r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L49)):*
> ```Python
>     with test_db_connection.cursor() as cur:
>         cur.execute("SELECT PiptUser_Id FROM PiptUser")
>         results = cur.fetchall()  # results are  type tuple of tuple
> ```

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
___
*[python/tests/sdb_sensitive.py, line 50 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefDtMAfbDiS9JRLP7:-MTefDtMAfbDiS9JRLP8:bq623e6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L50)):*
> ```Python
>         cur.execute("SELECT PiptUser_Id FROM PiptUser")
>         results = cur.fetchall()  # results are  type tuple of tuple
>         for pipt_user in results:
> ```

You could use list comprehension.
___
*[python/tests/sdb_sensitive.py, line 71 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefzbn3IrzrP4a6wgU:-MTefzbn3IrzrP4a6wgV:bseri5r) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L71)):*
> ```Python
>     with test_db_connection.cursor() as cur:
>         cur.execute("SELECT TargetCoordinates_Id FROM TargetCoordinates")
>         results = cur.fetchall()  # results are  type tuple of tuple
> ```

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
___
*[python/tests/sdb_sensitive.py, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefSdM4lD2L_6jaZSz:-MTefSdM4lD2L_6jaZT-:bq623e6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L73)):*
> ```Python
>         results = cur.fetchall()  # results are  type tuple of tuple
>         for target_coordinate in results:
>             target_coordinates_ids.append(target_coordinate[0])
> ```

You could use list comprehension.
___
*[python/tests/sdb_sensitive.py, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTegBgv3Cd8ajEAi-Do:-MTegBgv3Cd8ajEAi-Dp:b48loov) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L96)):*
> ```Python
>         sql += f"""
> Update Investigator
> SET  FirstName = {name}, Surname = {surname}, Email = {name}.{surname}@email.com, Phone = {random_phone_num_generator()}
> ```

I think you should use a library which can fake emails and phone numbers as well. Faker (https://faker.readthedocs.io/en/master/index.html) might be a good choice.
___
*[python/tests/sdb_sensitive.py, line 99 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefO1s8A6IDD2881U_:-MTefO1s8A6IDD2881Ua:b-gdsu2o) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L99)):*
> ```Python
> WHERE Investigator_Id = {investigator_id};
>         """
>         return sql
> ```

This only updates the first row.
___
*[python/tests/sdb_sensitive.py, line 119 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehMUL9UrI0fogzlre:-MTehMUL9UrI0fogzlrf:b-78x6cu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L119)):*
> ```Python
>         sql += f"""
> UPDATE PiptUser
> SET Username = user-{pipt_user_id}, Password = MD5(user-{pipt_user_id}-{os.getenv("SECRET_PASS")})
> ```

Might be faked as well, perhaps. (Faker has a user_name method.)
___
*[python/tests/sdb_sensitive.py, line 122 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiThgB-RS98GmdVpT:-MTeiThgB-RS98GmdVpU:b-gdsu2o) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L122)):*
> ```Python
> WHERE PiptUser_Id = {pipt_user_id};
>         """
>         return sql
> ```

This only updates the first row.
___
*[python/tests/sdb_sensitive.py, line 142 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehswREswnjW8YpFqe:-MTehswREswnjW8YpFqf:b-7lb19z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L142)):*
> ```Python
>         sql += f"""
> UPDATE TargetCoordinates
> SET RaH = {randint(0, 23)}, RaM = {randint(0, 59)}, DecD = {randint(0, 75)}, DecM = {randint(0, 59)}
> ```

What about the seconds? And the declination sign?
___
*[python/tests/sdb_sensitive.py, line 145 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiPt_A9T1gVVU8LrM:-MTeiPt_A9T1gVVU8LrN:b-bm2xr2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L145)):*
> ```Python
> WHERE TargetCoordinates_Id = {target_coordinates_id};      
>         """
>     return sql
> ```

This only updates the last row.
___
*[python/tests/util.py, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiAJJCEajSACyX-Gk:-MTeiAJJCEajSACyX-Gl:b-rqnc9s) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/util.py#L2)):*
> ```Python
> import random
> ```

Should not be necessary, depending on the library used for faking data.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[python/pyproject.toml, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeef3BBg1pypAXMGFo:-MTknXFo4McUvKsvKC8I:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/pyproject.toml#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure whether Poetry assumes the name to be the same as the code directory. I'd rather leave it as app.
</blockquote></details>

Done.
___
*[python/tests/create_test_database.py, line 72 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeil9T7hHR_b6P-9vO:-MTkej7g2qMMgQx3sHCp:b2filjo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/create_test_database.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These comments might suggest splitting up the function.
</blockquote></details>

splited
___
*[python/tests/sdb_sensitive.py, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefiVw7DL79gnDtNlm:-MTkfxIa66jQwDck8wPR:bookngf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
</blockquote></details>

is it python hint from typings
___
*[python/tests/sdb_sensitive.py, line 28 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefZGQA9C-9NsgrrQk:-MTkfyPCBKyszdFZMiep:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could use list comprehension.
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefvaH3AF0wFlQ_tVT:-MTkfyzC-s68FGpQnkSL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 50 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefDtMAfbDiS9JRLP7:-MTkfzYo06urTlqXFwGk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could use list comprehension.
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 71 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefzbn3IrzrP4a6wgU:-MTkg-8n1GSVTr7c4Z3w:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note sure the comment is necessary. (If you want to include the information, why not use a type hint if need be?)
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefSdM4lD2L_6jaZSz:-MTkg09zABnmegs5iHdj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could use list comprehension.
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTegBgv3Cd8ajEAi-Do:-MTknaJkAyu5XrNhATi-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should use a library which can fake emails and phone numbers as well. Faker (https://faker.readthedocs.io/en/master/index.html) might be a good choice.
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 99 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefO1s8A6IDD2881U_:-MTkglHx6njLT-c_zY20:bb6un1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This only updates the first row.
</blockquote></details>

Done
___
*[python/tests/sdb_sensitive.py, line 119 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehMUL9UrI0fogzlre:-MTko1aa7CctnBDSTwb_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might be faked as well, perhaps. (Faker has a user_name method.)
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 122 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiThgB-RS98GmdVpT:-MTko3BN1QVGzNq7w7Bj:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L122)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This only updates the first row.
</blockquote></details>

fixed
___
*[python/tests/sdb_sensitive.py, line 142 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehswREswnjW8YpFqe:-MTkqq4O0KPZVK7NJbyj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L142)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about the seconds? And the declination sign?
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 145 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiPt_A9T1gVVU8LrM:-MTkphuuCMMBMi0lpsSu:bd75mla) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This only updates the last row.
</blockquote></details>

This one actully it wasn't buggy
___
*[python/tests/util.py, line 2 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiAJJCEajSACyX-Gk:-MTkpkmQ71VK29uWGDfd:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/util.py#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be necessary, depending on the library used for faking data.
</blockquote></details>

removed

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MToP2W13ia3ipfPu7u8:-MToP2W13ia3ipfPu7u9:bvlpm37) (no related file):*
There probably should only be a single file for this.

And you might consider defining a command for executing the script.

---
___
*[python/tests/sdb_sensitive.py, line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTefiVw7DL79gnDtNlm:-MToMEyl6qOvHedc3l37:b2nhswy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

is it python hint from typings
</blockquote></details>

Yes
___
*[python/tests/sdb_sensitive.py, line 142 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehswREswnjW8YpFqe:-MToLRakChpv7IFic12t:bbuulz9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L142)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But now you generate target coordinates which are not accessible by SALT...
___
*[python/tests/sdb_sensitive.py, line 145 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiPt_A9T1gVVU8LrM:-MToL_719CkaLcASKLst:b-rhixp9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L145)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This one actully it wasn't buggy
</blockquote></details>

I still have serious doubts regarding the SQL in all these functions.
___
*[python/tests/sdb_sensitive.py, line 110 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MToNEPlBYH0Gro5_T_X:-MToNEPlBYH0Gro5_T_Y:bjguej5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0e547274adc1a7fab62ca2988c880a0ef707eee1/python/tests/sdb_sensitive.py#L110)):*
> ```Python
>     for pipt_user_id in pipt_user_ids:
>         sql += f"""UPDATE PiptUser
> SET Username = user-{fake.user_name()}, Password = MD5(user-{pipt_user_id}-{os.getenv("SECRET_PASS")})
> ```

SECRET_PASS > TEST_DB_USER_PASSPHRASE (or something like that)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MToP2W13ia3ipfPu7u8:-MTuCOjs6CHzMGg4Z3wZ:b-896fix) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There probably should only be a single file for this.

And you might consider defining a command for executing the script.
</blockquote></details>

Done.

---
___
*[python/pyproject.toml, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeepqNEun8SUEfxpDG:-MTuBt-LCCca0LfkI8Kf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/pyproject.toml#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Might need discussion.
</blockquote></details>

Done.
___
*[python/tests/sdb_sensitive.py, line 142 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTehswREswnjW8YpFqe:-MTuCBm80QRlLGJSzJIr:b-qssebl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L142)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But now you generate target coordinates which are not accessible by SALT...
</blockquote></details>

fixed.
___
*[python/tests/sdb_sensitive.py, line 145 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeiPt_A9T1gVVU8LrM:-MTuCFhxBboF5sXWrNqQ:bemc3o2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/sdb_sensitive.py#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still have serious doubts regarding the SQL in all these functions.
</blockquote></details>

no nongle applicable
___
*[python/tests/sdb_sensitive.py, line 110 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MToNEPlBYH0Gro5_T_X:-MTuC8rpA43-Lh6_2cHX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/0e547274adc1a7fab62ca2988c880a0ef707eee1/python/tests/sdb_sensitive.py#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

SECRET_PASS > TEST_DB_USER_PASSPHRASE (or something like that)
</blockquote></details>

Done.
___
*[python/tests/create_test_database.py, line 39 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MTeicc-6JwZSZox6zN3:-MTuCJq-5sFOoOvk9zew:b-qssebl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7c8f7f2479b79ed43e59c14a92dc01a90a72d3b1/python/tests/create_test_database.py#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The uppercase variables are unnecessary.
</blockquote></details>

fixed.

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 2 of 4 files at r4, 1 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: 1 of 5 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[python/tests/create_test_database.py, line 178 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MUNSxfiBAfkTanlUDu9:-MUNSxfiBAfkTanlUDuA:b-giw0wc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c4e380fc5258a69f2987ce9eee6d4941496068aa/python/tests/create_test_database.py#L178)):*
> ```Python
>     """
>     cursor = await test_db_connection.cursor()
>     await cursor.executemany(sql, data)
> ```

this should not be waited
___
*[python/tests/create_test_database.py, line 204 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MUNSuJECBpDWOts8Mxt:-MUNSuJECBpDWOts8Mxu:b-giw0wc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c4e380fc5258a69f2987ce9eee6d4941496068aa/python/tests/create_test_database.py#L204)):*
> ```Python
>     """
>     cursor = await test_db_connection.cursor()
>     await cursor.executemany(sql, data)
> ```

this should not be waited
___
*[python/tests/create_test_database.py, line 249 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/3#-MUNSgGQD35qWiLlaXu1:-MUNSgGQD35qWiLlaXu2:b6nw9gh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c4e380fc5258a69f2987ce9eee6d4941496068aa/python/tests/create_test_database.py#L249)):*
> ```Python
>     """
>     cursor = await test_db_connection.cursor()
>     await cursor.executemany(sql, data)
> ```

I thought you said such process doesn't need to be waited

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 4 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: all files reviewed, 11 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
