### PR TITLE
Authentication and obs comments from PR #81

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/82)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 28 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/82)* status: 28 of 37 files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[cypress/integration/forgot-password.spec.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxsSkO1BCeYb2zr7kv:-MlxsSkO1BCeYb2zr7kw:b-m6jo01) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/cypress/integration/forgot-password.spec.ts#L75)):*
> ```XML
>     cy.get('@emails').should('have.length', 1);
> 
>     // And it is sent to the correct email address
> ```

This you will never know.
___
*[src/app/app.component.html, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlxzwf1CfLDoIh3XvBY:-Mlxzwf1CfLDoIh3XvBZ:bt13pk2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/app.component.html#L8)):*
> ```HTML
>   <div class="left">
>     <a [routerLink]="['/']">Home</a>
>     <input type="button" id="login" value="Login" />
> ```

I do not understand why you have this input.
It is not doing anything and doesn't have bulma classes
___
*[src/app/app.component.html, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxzkcnDtdLE77nOGkJ:-MlxzkcnDtdLE77nOGkK:b-ksau9u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/app.component.html#L10)):*
> ```HTML
>     <input type="button" id="login" value="Login" />
>     
>   </div>
> ```

This condition is always false some how please double check it
___
*[src/app/app.component.html, line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxxdMiC-owp0ZUcEvT:-MlxxdMiC-owp0ZUcEvU:b3fyhru) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/app.component.html#L18)):*
> ```HTML
>   </div>
>   <ng-template #inlineLoginForm>
>     <div class="right">
> ```

bulma css `is-pulled-right` does this
___
*[src/app/app.component.scss, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxxqWw2miVHWh32S93:-MlxxqWw2miVHWh32S94:bh7ejrw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/app.component.scss#L7)):*
> ```SCSS
> }
> 
> .right {
> ```

 bulma css `is-pulled-right` does this.
please confirm margin it is out of line
___
*[src/app/home/home-guest/home-guest.component.html, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxuwOf56FXbhhK_mWB:-MlxuwOf56FXbhhK_mWC:b-z419ws) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/home/home-guest/home-guest.component.html#L3)):*
> ```HTML
> <h1 class="title is-1">Welcome to the Web Manager</h1>
> 
> <p>Please login to get started.</p>
> ```

text is almost invinsible above such a big heading
___
*[src/app/home/home-user/home-user.component.html, line 74 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlxu4sH7fP2XPnHw5Yo:-Mlxu4sH7fP2XPnHw5Yp:bstqqmc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/home/home-user/home-user.component.html#L74)):*
> ```HTML
>       <option value="2024-2">2024-2</option>
>       <option value="2025-1">2025-1</option>
>       <option value="2025-2">2025-2</option>
> ```

In exatly 4 years we will have to extend this list manually.
this is bad we need and end point for getting semesters
___
*[src/app/inline-login/inline-login.component.html, line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlxwv1NDC0sLFxw70TU:-Mlxwv1NDC0sLFxw70TV:b-v8tnw4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L2)):*
> ```HTML
> <form data-test="inline-login" [formGroup]="loginForm" (ngSubmit)="login()">
>   <div>
> ```

the should be some spaces between inputs
___
*[src/app/inline-login/inline-login.component.html, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlxwl5P0jLCncW0p1Rk:-Mlxwl5P0jLCncW0p1Rl:b5g5vth) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L3)):*
> ```HTML
> <form data-test="inline-login" [formGroup]="loginForm" (ngSubmit)="login()">
>   <div>
>     <input
> ```

This should have an `input` class for bulma.
___
*[src/app/inline-login/inline-login.component.html, line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxworP5cAtsJhyhlsI:-MlxworP5cAtsJhyhlsJ:b5g5vth) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L10)):*
> ```HTML
>       data-test="inline-login-username"
>     />
>     <input
> ```

This should have an `input` class for bulma.
___
*[src/app/inline-login/inline-login.component.html, line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlxx68UBmUMqjuyRoA1:-Mlxx68UBmUMqjuyRoA2:bl02exy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L15)):*
> ```HTML
>       formControlName="password"
>       placeholder="Password"
>       data-test="inline-login-password"
> ```

button to not shaow loading
addind `is-loading` class while loading will help 
___
*[src/app/inline-login/inline-login.component.html, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MlxwOlZ3kpPN5jZ2hwA:-MlxwOlZ3kpPN5jZ2hwB:b7psh82) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L17)):*
> ```HTML
>       data-test="inline-login-password"
>     />
>     <input
> ```

This should have a button class for bulma.
you you said this should be a button not input 
___
*[src/app/inline-login/inline-login.component.ts, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlz2vOAAlBcfdVMfVEN:-Mlz2vOB3OsIo2w9484f:b2tq9e9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.ts#L50)):*
> ```XML
>       .login(this.f.username.value, this.f.password.value)
>       .subscribe(
>         (data: AccessToken) => {
> ```

data not used,
AccessToken not set. mybe that is why it doesn't log in
___
*[src/app/service/real/real-authentication.service.ts, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlz3ukLAFZL-x9O_DHd:-Mlz3ukM7WpMQRkYFLIe:b-c1amaq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/service/real/real-authentication.service.ts#L44)):*
> ```XML
>       tap((tokenData) => {
>         this.setAccessToken(tokenData);
>         this;
> ```

`this;` have no affect
___
*[src/app/service/real/real-authentication.service.ts, line 91 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mly07bvBYw6os43s_Sv:-Mly07bvBYw6os43s_Sw:bbk351i) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/service/real/real-authentication.service.ts#L91)):*
> ```XML
>         .pipe(
>           switchMap(() => {
>             console.log('OOOO', this.isAuthenticated());
> ```

debug statements should be removed

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/82)* status: 28 of 37 files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/inline-login/inline-login.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-Mlz58a54EnOcMDYnEKV:-Mlz58a54EnOcMDYnEKW:b-s7ve4v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/2f6094bd66116cb7cf72a0e15e79ec7b7553f216/src/app/inline-login/inline-login.component.html#L1)):*
> ```HTML
> <form data-test="inline-login" [formGroup]="loginForm" (ngSubmit)="login()">
> ```

with this on the line it renders log in page useless.
you might aswell add a forget password link and get rid of the login page.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 2 of 37 files at r1, 3 of 19 files at r2, 12 of 14 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/82)* status: 48 of 49 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[src/app/navigation-bar/navigation-bar.component.spec.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MnZdMbo2B3p8U2r_9-v:-MnZdMbp566RYYZVUbU5:bigp4c3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cca09b84976b709f994150c1cde2c9e859cfdc39/src/app/navigation-bar/navigation-bar.component.spec.ts#L1)):*
> ```XML
> import { ComponentFixture, TestBed } from '@angular/core/testing';
> ```

this file should be removed
it is testing nothing.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/82)* status: 48 of 49 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/app/navigation-bar/navigation-bar.component.spec.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/82#-MnZdMbo2B3p8U2r_9-v:-Mn_qSZe9Zsb-AmpaD6q:bbxym39) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cca09b84976b709f994150c1cde2c9e859cfdc39/src/app/navigation-bar/navigation-bar.component.spec.ts#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this file should be removed
it is testing nothing.
</blockquote></details>

It is true it isn't testing much (other than that the component is loading). But the same can be said for many of the other test files as well, and as long as the test passes, I'd suggest not to remove the file.

**Pull request merged**
