### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Fixed workflow errors for test and deploy actions

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdX_8i-Eq0R2sL76Bjs:-MdX_8i-Eq0R2sL76Bjt:bbswmnk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/service/user.py#L44)):*
> ```Python
> ON DUPLICATE KEY UPDATE Username=%(username)s
> """
>     if not isinstance(db, dict):  # skip this part when performing tests
> ```

a) Is a db pool really an instance of dict?

b) I'd be apprehensive of catering for tests in the code.
___
*[python/app/util/authentication.py, line 84 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXaEaDBXwAokog7hbE:-MdXaEaE4Qem34DDU9Cf:b-tz6hin) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/util/authentication.py#L84)):*
> ```Python
> def get_new_password_hash(password: str) -> str:
>     """Hash a plain text password."""
>     return cast(str, pwd_context.hash(password))
> ```

Maybe add a comment that the type hint for the return value of the hash method is Any, but that the method is guaranteed to return a str?
___
*[python/tests/conftest.py, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXc8_YCkRv-nVtoxTF:-MdXc8_YCkRv-nVtoxTG:bom9ume) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/243f9b8670e075d6da5e44e6cc75f7b85c3333eb/python/tests/conftest.py#L3)):*
> ```Python
> import os
> 
> import dotenv
> ```

I don't think these lines should have been moved.

 Now I remember why there are the noqa comments --flake8 doesn't like import statement that aren't at thew top of the file.
___
*[python/tests/conftest.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcl7AAE8NtnyBF_PO:-MdXcl7AAE8NtnyBF_PP:bmbrvl0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L41)):*
> ```Python
> 
> @pytest.fixture()
> @nodatabase
> ```

Not necessary, I think.
___
*[python/tests/conftest.py, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcoaA2azDokTWCVO8:-MdXcoaA2azDokTWCVO9:bmbrvl0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L75)):*
> ```Python
> 
> @pytest.fixture()
> @nodatabase
> ```

Not necessary, I think.
___
*[python/tests/test_dependencies.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXd1_b56M6zXh6Dk13:-MdXd1_b56M6zXh6Dk14:b-wpvkpj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/test_dependencies.py#L50)):*
> ```Python
> )
> @pytest.mark.asyncio
> @nodatabase
> ```

Are you sure all there new @nodatabase decorators in this file are necessary?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdX_8i-Eq0R2sL76Bjs:-MdXhL-p9nmPN6rFHFUL:b-rw9tdm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/service/user.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a) Is a db pool really an instance of dict?

b) I'd be apprehensive of catering for tests in the code.
</blockquote></details>

a) This is the case when running the tests because db comes in as a dictionary and as such this gives an error in the line below (line 45) since db is as dict so it doesn't have a method acquire. So the test only passed when I added this check.

b) I must agree with you, I wasn't sure where to put it. I guess it is safe to say it must be put somewhere in the tests directory, maybe test_user script?
___
*[python/tests/conftest.py, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXc8_YCkRv-nVtoxTF:-MdXlGT73fJdcwbo5qG2:bdo257k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/243f9b8670e075d6da5e44e6cc75f7b85c3333eb/python/tests/conftest.py#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think these lines should have been moved.

 Now I remember why there are the noqa comments --flake8 doesn't like import statement that aren't at thew top of the file.
</blockquote></details>

After reading a bit about flake8 that's what I also thought but after making changes to the code flake8 still complained when I put import at the top. However, after making the changes you see currently flake8 was happy and the tests passed.
___
*[python/tests/conftest.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcl7AAE8NtnyBF_PO:-MdXn9nk5aaSC6qgu8xA:b-2fbp7o) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not necessary, I think.
</blockquote></details>

Okay, I'll remove it.
___
*[python/tests/conftest.py, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcoaA2azDokTWCVO8:-MdXnHN6CIMREGbKFuCk:b9vlpxg) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not necessary, I think.
</blockquote></details>

I'll remove it.
___
*[python/tests/test_dependencies.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXd1_b56M6zXh6Dk13:-MdXnLnh7BFxXUbyEn8T:b-rlxkrh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/test_dependencies.py#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you sure all there new @nodatabase decorators in this file are necessary?
</blockquote></details>

I am not sure but it seemed to be a fix some errors I was facing. In a way, it made sense to me because these functions are using the database. But since i am not sure i will remove this decorator and make sure it has not effect.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[python/app/util/authentication.py, line 84 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXaEaDBXwAokog7hbE:-MdXqf95DrR5DBbLEFso:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/util/authentication.py#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment that the type hint for the return value of the hash method is Any, but that the method is guaranteed to return a str?
</blockquote></details>

Done.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdX_8i-Eq0R2sL76Bjs:-Mda2QoM3S1oq8ouiVTN:bs7wumx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/service/user.py#L44)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

a) This is the case when running the tests because db comes in as a dictionary and as such this gives an error in the line below (line 45) since db is as dict so it doesn't have a method acquire. So the test only passed when I added this check.

b) I must agree with you, I wasn't sure where to put it. I guess it is safe to say it must be put somewhere in the tests directory, maybe test_user script?
</blockquote></details>

Done. 
___
*[python/tests/conftest.py, line 41 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcl7AAE8NtnyBF_PO:-Mda2M_85NykyH2gzHIm:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L41)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Okay, I'll remove it.
</blockquote></details>

Done.
___
*[python/tests/conftest.py, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXcoaA2azDokTWCVO8:-Mda2LV8AqtqPhPzEygf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/conftest.py#L75)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I'll remove it.
</blockquote></details>

Done.
___
*[python/tests/test_dependencies.py, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXd1_b56M6zXh6Dk13:-Mda2DmW82fXhg8tK6vv:b-taubo1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/tests/test_dependencies.py#L50)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am not sure but it seemed to be a fix some errors I was facing. In a way, it made sense to me because these functions are using the database. But since i am not sure i will remove this decorator and make sure it has not effect.
</blockquote></details>

You were right, I didn't need those decorators.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdX_8i-Eq0R2sL76Bjs:-MdYntRL1KxF6Q28kmPI:bu8fmfq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/service/user.py#L44)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

a) This is the case when running the tests because db comes in as a dictionary and as such this gives an error in the line below (line 45) since db is as dict so it doesn't have a method acquire. So the test only passed when I added this check.

b) I must agree with you, I wasn't sure where to put it. I guess it is safe to say it must be put somewhere in the tests directory, maybe test_user script?
</blockquote></details>

a) Ah, sorry, I clearly overlooked the "not"...

b) You should make sure that the test does not call the method. You might have to mock it in the failing test(s).
___
*[python/app/util/authentication.py, line 84 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXaEaDBXwAokog7hbE:-Mda87d6DI0L3N_Vxrjo:b7zprim) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ddd1d913761781d80d3b60d7b957ce4f236fae71/python/app/util/authentication.py#L84)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! This is absolutely nit-picking, I wouldn't include this comment on what is essentially a comment about an implementation detail in the docstring
___
*[python/tests/conftest.py, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdXc8_YCkRv-nVtoxTF:-Mda8yD5BM5ab07AJz1T:bvkx37) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/243f9b8670e075d6da5e44e6cc75f7b85c3333eb/python/tests/conftest.py#L3)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

After reading a bit about flake8 that's what I also thought but after making changes to the code flake8 still complained when I put import at the top. However, after making the changes you see currently flake8 was happy and the tests passed.
</blockquote></details>

The trouble is that by then it might be too late, and you have read in environment variables from `.env` rather than `.env.test` already. Ands I've just double-checked; flake8 is happy even if you put the lines at the top.
___
*[python/tests/util/test_auth.py, line 145 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdaAVA22yFFTmSOjOoz:-MdaAVA22yFFTmSOjOp-:b86cuff) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ebdc5611c0f347d4275ece61059bd2666781554/python/tests/util/test_auth.py#L145)):*
> ```Python
> 
>     async def mock_update_password_hash(username: str, password: str, db: Pool) -> None:
>         """Returns None for updating password hash."""
> ```

Nit-picking again: This docstring is somewhat unnecessary. :-)
___
*[python/tests/util/test_auth.py, line 177 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-MdaAgy9BUR83Mq7jNe7:-MdaAgy9BUR83Mq7jNe8:b86cuff) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5ebdc5611c0f347d4275ece61059bd2666781554/python/tests/util/test_auth.py#L177)):*
> ```Python
> 
>     async def mock_update_password_hash(username: str, password: str, db: Pool) -> None:
>         """Returns None for updating password hash."""
> ```

Nit-picking again: This docstring is somewhat unnecessary. :-)

**Review by hettlage — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/47#-:-MdaJe5VAJpel5Oo8pue:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Pull request merged**
