### PR TITLE
Authentication functionality

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/2)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 22 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/2)* status: 32 of 35 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[docs/implementation.md, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_1R4o3zc5GL29S3t0:-MT_1R4o3zc5GL29S3t1:bws2egc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/docs/implementation.md#L5)):*
> ```Markdown
> ## Authentication
> 
> The Web Manager and the API use OAuth 2, as described in the FastAPI documentation. However, there is a twist: The user can authenticate not only with an Authorization header, but also with an Authorization cookie. In both cases the header or cookie value must be of the bearer format,
> ```

 However, there is a twist: The user can authenticate not only with an Authorization header, but also with an Authorization cookie ->
 However, the user can authenticate not only with an Authorization header, but also with an Authorization cookie
___
*[python/pyproject.toml, line 11 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_2BCA0MS7IC6Xvka_:-MT_2BCA0MS7IC6Xvkaa:b-7at05x) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/pyproject.toml#L11)):*
> ```TOML
> fastapi = "^0.63.0"
> uvicorn = "^0.13.3"
> pytest-asyncio = "^0.14.0"
> ```

Isn't this a dev dependency.
___
*[python/app/service/user.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_3e6j1mmBr8oIYEBD:-MT_3e6j1mmBr8oIYEBE:b-1bioe6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/app/service/user.py#L8)):*
> ```Python
> def get_user(username: str) -> UserInDB:
>     return UserInDB(
>         username=username, hashed_password=auth.get_password_hash("!" + username)
> ```

why are you adding the "!" to the auth.get_password_hasd and why the username and not password?
___
*[python/app/util/auth.py, line 64 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_4P2z8G2eo6RxyuVi:-MT_4P2z8G2eo6RxyuVj:bmd3bak) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/app/util/auth.py#L64)):*
> ```Python
> 
> 
> def get_password_hash(password: str) -> str:
> ```

what is the exact use of this method.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/2)* status: 30 of 35 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[docs/implementation.md, line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_1R4o3zc5GL29S3t0:-MT_I08g5wnfGnel3hMV:bbvhrqf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/docs/implementation.md#L5)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

 However, there is a twist: The user can authenticate not only with an Authorization header, but also with an Authorization cookie ->
 However, the user can authenticate not only with an Authorization header, but also with an Authorization cookie


</blockquote></details>

Wording changed.
___
*[python/pyproject.toml, line 11 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_2BCA0MS7IC6Xvka_:-MT_I3fdAUPnIN4RcAj3:b-ky41u1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/pyproject.toml#L11)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Isn't this a dev dependency.
</blockquote></details>

Yup. Thanks!
___
*[python/app/service/user.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_3e6j1mmBr8oIYEBD:-MT_BSYS1MkqpGvOzy86:b-m467th) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/app/service/user.py#L8)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

why are you adding the "!" to the auth.get_password_hasd and why the username and not password?
</blockquote></details>

This is a placeholder function, really, and will be replaced with a proper one once there is database integration.
___
*[python/app/util/auth.py, line 64 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/2#-MT_4P2z8G2eo6RxyuVi:-MT_I7hc8S3ISBI3GYRc:b-46cql1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/83d6d53f4fbe5551c6882930de365b2bf6df7bc1/python/app/util/auth.py#L64)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

what is the exact use of this method.
</blockquote></details>

Might be easier to clarify in a quick chat?

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 26 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/2)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
