### PR TITLE
time allocation and charged time.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/types.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoDIH5jfK0bPxtaxS:-MaJoDIH5jfK0bPxtaxT:b-5y1xli) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L16)):*
> ```XML
> }
> 
> export interface Allocation {
> ```

Allocation --> TimeAllocation
___
*[frontend/src/app/types.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoIfwBdYW9xVD680M:-MaJoIfwBdYW9xVD680N:b-ft8ze3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L28)):*
> ```XML
> export interface Proposal {
>   investigators: Investigator[];
>   allocations: Allocation[]
> ```

allocations --> time_allocations
___
*[frontend/src/app/types.ts, line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoTF8EYSv9hXB_8m6:-MaJoTF8EYSv9hXB_8m7:b-zbvvof) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L32)):*
> ```XML
> }
> 
> export interface ChargeTime {
> ```

ChargeTime --> ChargedTime
___
*[frontend/src/app/proposal/allocation-table/allocation-table.component.html, line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJrpOX1Kjrh0u7x22o:-MaJrpOX1Kjrh0u7x22p:blec4at) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/proposal/allocation-table/allocation-table.component.html#L23)):*
> ```HTML
>       <div>{{ a.priority_3 }}</div>
>       <div>{{ a.priority_4 }}</div>
>       <div *ngIf="!!a.tac_comment"><button mat-raised-button
> ```

I would propose to use a link rather than a button, as in the existing WM.
___
*[frontend/src/app/proposal/allocation-table/allocation-table.component.ts, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJrYOp11XOaq7ajWit:-MaJrYOp11XOaq7ajWiu:b-e6r110) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/proposal/allocation-table/allocation-table.component.ts#L5)):*
> ```XML
> 
> @Component({
>   selector: 'wm-allocation-table',
> ```

wm-allocation-table ---> wm-time-allocation-table
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts, line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJq4Kd10A5nBiF4_q6:-MaJq4Kd10A5nBiF4_q7:b-yfl8rb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts#L11)):*
> ```XML
> export class ChargedTimeTableComponent implements OnInit {
>   @Input() charged_time!: ChargeTime
>   @Input() allocated_total!: number
> ```

I would propose to pass the time allocations instead of a total allocation value. The fact that you add up P1 to P3 is very specific to this table, and you shouldn't bother about it outside the tables -- not least because you would have to choose a name like allocated_p1_to_p3_time (to avoid ambiguity), which doesn't look nice to me.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 4 of 58 files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoDIH5jfK0bPxtaxS:-MacpLXQ6O9Q-E7QwRUr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Allocation --> TimeAllocation
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoIfwBdYW9xVD680M:-MacpY1cDf2J0-SWqCJU:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

allocations --> time_allocations
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MaJoTF8EYSv9hXB_8m6:-Macpd4TAL1looDHZoGd:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/8ab5bc185067503341ac4ad265579fdd9a507a78/frontend/src/app/types.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ChargeTime --> ChargedTime
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
General remarks:

* Given the amount of files, I'd be worried that you end up undoing changes in the development branch when merging.
* Numbers should be right-aligned.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-:-MbFvT37-uiWvb8sxupS:b-b8f3o5)* status: 2 of 58 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/proposal/allocation-table/time-allocation-table.component.html, line 23 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbFwMw87r41EZccx0tn:-MbFwMw87r41EZccx0to:b-91vp9m) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cd2edc968ae85eb27a286ba32cc7f0022e76132/frontend/src/app/proposal/allocation-table/time-allocation-table.component.html#L23)):*
> ```HTML
>       <div *ngIf="!!a.tac_comment">
>         <span
>           class="has-text is-link"
> ```

has-text is-link ---> has-text-link
___
*[frontend/src/app/proposal/allocation-table/time-allocation-table.component.html, line 27 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbFw36i356eb9HrNPcd:-MbFw36j5Nr-lvE2xPiv:b-e6swz8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3cd2edc968ae85eb27a286ba32cc7f0022e76132/frontend/src/app/proposal/allocation-table/time-allocation-table.component.html#L27)):*
> ```HTML
>         > Show comment</span>
>       </div>
>       <div *ngIf="!a.tac_comment"><div class="tag is-light">No comment</div></div>
> ```

I don't think this should be styled as a tag.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2, 4 of 7 files at r3, 6 of 35 files at r4, 6 of 15 files at r5, 3 of 5 files at r6, 7 of 9 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 33 of 58 files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

*[a discussion](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLz0M-EvCsanGdxsI-:-MbLz0M-EvCsanGdxsI0:b-c5gemp) (no related file):*
I'm worried that you might undo other changes when merging this branch.

---
___
*[frontend/.gitignore, line 43 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLUZNa3FRJ3RBnfg_e:-MbLUZNa3FRJ3RBnfg_f:b-t4gq9j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/.gitignore#L43)):*
> ```ignore
> testem.log
> /typings
> yarn.lock
> ```

Lock files should not be ignored. (Unless you did this deliberately as there is a package-lock.json file as well?)
___
*[frontend/src/app/proposal/allocation-table/tac-comment-data-dialog.html, line 1 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLsg0xDcDIC4zgkaDO:-MbLsg0xDcDIC4zgkaDP:b3l8g7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/allocation-table/tac-comment-data-dialog.html#L1)):*
> ```HTML
> <div class="table">
> ```

Why the "data" in the name? And why do you pass a data object rather than a message string?

And do you use this file anywhere?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 20 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLxnBq13r80rgwaJDY:-MbLxnBq13r80rgwaJDZ:bp26cel) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L20)):*
> ```HTML
>       <div>{{ charged_time.priority_4 }}</div>
>       <div>
>         {{ charged_time.priority_0 + charged_time.priority_1 + charged_time.priority_2 + charged_time.priority_3}}/
> ```

Why do you use a variable for one sum (allocated time) but not for the other (charged time)?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 25 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLykViD7h5lBzdfjol:-MbLykViD7h5lBzdfjom:bst94sn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L25)):*
> ```HTML
>       <div>
>         {{(
>         (charged_time.priority_0 + charged_time.priority_1 + charged_time.priority_2 + charged_time.priority_3)/
> ```

You could consider adding a unit test testing that the correct values are shown.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 26 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLwfIpBa0iV9Pyq-Sg:-MbLwfIpBa0iV9Pyq-Sh:b-d0lkw3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L26)):*
> ```HTML
>         {{(
>         (charged_time.priority_0 + charged_time.priority_1 + charged_time.priority_2 + charged_time.priority_3)/
>         allocated_p1_to_p3_time)*100 | number : '1.0-2'
> ```

I think there should be one decimal at most.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts, line 12 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLy1AD8In8Mk8YbwZn:-MbLy1AD8In8Mk8YbwZo:b22iyxj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts#L12)):*
> ```XML
>   @Input() charged_time!: ChargedTime
>   @Input() time_allocations!: TimeAllocation
>   allocated_p1_to_p3_time: number = 0
> ```

allocated_p1_to_p3_time ---> allocated_p0_to_p3_time
___
*[frontend/src/app/proposal/allocation-table/time-allocation-table.component.scss, line 11 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLszIi4INd0ysmcyvz:-MbLszIi4INd0ysmcyw-:b-nh7lwf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/allocation-table/time-allocation-table.component.scss#L11)):*
> ```SCSS
>   align-items: center;
> }
> .tooltip-local {
> ```

Why the "-local" in the class names?

And why do you need all these classes?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 35 files at r4, 17 of 17 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 38 of 59 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/package.json, line 18 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-Mbfj0P22wW4qK2058zi:-Mbfj0P22wW4qK2058zj:b4d8k2o) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/package.json#L18)):*
> ```JSON
>     "@angular/core": "~12.0.0",
>     "@angular/forms": "~12.0.0",
>     "@angular/material": "^12.0.3",
> ```

Shouldn't that be removed?
___
*[frontend/src/styles.scss, line 7 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbfjAXjEClidvaL6NUT:-MbfjAXjEClidvaL6NUU:belppap) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/styles.scss#L7)):*
> ```SCSS
> $light-strip: #eeeeee;
> $dark-strip: #dddddd;
> $secondary-header: #666;
> ```

If you have changed #eee to #eeeeee and #ddd to $#dddddd, why haven't you changed #666 to #666666?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 19 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbfjfEH47R69sDWnnPP:-MbfjfEH47R69sDWnnPQ:b-wch89l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L19)):*
> ```HTML
>       <div>{{ charged_time.priority_3 }}</div>
>       <div>{{ charged_time.priority_4 }}</div>
>       <div class="data-test-total-allocated">
> ```

Why do you have a class "data-test-total-allocated"?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts, line 11 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-Mbfkh337rAS6LgJrpB0:-Mbfkh337rAS6LgJrpB1:bzfwn1f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts#L11)):*
> ```XML
> export class ChargedTimeTableComponent implements OnInit {
>   @Input() charged_time!: ChargedTime
>   @Input() time_allocations!: TimeAllocation
> ```

time_allocations ---> time_allocation (as the type name is singular)
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 31 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbfsSBaE4SaxjcCfFrJ:-MbfsSBaE4SaxjcCfFrK:bppli4z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L31)):*
> ```XML
>   it('should have completion of 42.9%', () => {
>     const completion = fixture.nativeElement.querySelector('div.data-test-completion')
>     //Todo: I some how fail to get this element
> ```

Let's chat about this.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 26 of 59 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/package.json, line 18 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-Mbfj0P22wW4qK2058zi:-Mbg-sd403nQ-Yw41Q6U:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/package.json#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be removed?
</blockquote></details>

Done.
___
*[frontend/src/styles.scss, line 7 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbfjAXjEClidvaL6NUT:-MbhGyRt1TP2qMlMsMX0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/styles.scss#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you have changed #eee to #eeeeee and #ddd to $#dddddd, why haven't you changed #666 to #666666?
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 25 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbLykViD7h5lBzdfjol:-MbhH4-y8hCtVobxx5eK:b-7tfmjp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4a2de572cf8021682e8cad80b4bcbefdad55f3bd/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could consider adding a unit test testing that the correct values are shown.
</blockquote></details>

added
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 19 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbfjfEH47R69sDWnnPP:-MbhH2nZEz7nh2qgDLE0:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you have a class "data-test-total-allocated"?
</blockquote></details>

removed
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts, line 11 at r9](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-Mbfkh337rAS6LgJrpB0:-Mbg15PnEoVDrxYEIOy2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7258993b2cf5ac6b9146545f79d4fd5943b87424/frontend/src/app/proposal/charged-time-table/charged-time-table.component.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

time_allocations ---> time_allocation (as the type name is singular)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 38 of 59 files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/package.json, line 28 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhJlKC9OyHVmUtXadT:-MbhJlKC9OyHVmUtXadU:bbuldze) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/package.json#L28)):*
> ```JSON
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.1102.14",
> ```

This version change looks really odd to me.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 19 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhKCd_89IlQB3paqB4:-MbhKCd_89IlQB3paqB5:bldtjld) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L19)):*
> ```HTML
>       <div>{{ charged_time.priority_3 }}</div>
>       <div>{{ charged_time.priority_4 }}</div>
>       <div data-testid = "total-allocated">
> ```

Maybe better `data-testid = "absolute-completion"`?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 22 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhKbZO2cJoRrN5DmI9:-MbhKbZO2cJoRrN5DmIA:bu4od7w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L22)):*
> ```HTML
>         {{ charged_time_p0_to_p3}}/{{allocated_p0_to_p3_time}}
>       </div>
>       <div data-testid = "completion">
> ```

Maybe better `data-testid="relative-completion"`?
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 2 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhL-cE3O1a1fO2dGGS:-MbhL-cE3O1a1fO2dGGT:bq8nz8t) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L2)):*
> ```XML
> import { ComponentFixture, TestBed } from '@angular/core/testing';
> import {proposal} from "../../mock/proposal-data";
> ```

I don't think importing the mock proposal is necessary - the component doesn't care where the time allocation / completion values come from. Also, it makes the tests more brittle (someone might change the mock data...) and harder to follow.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 22 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhLrxJ6QAyC42GoSP1:-MbhLrxKD-VfrwYu5lOo:b5non35) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L22)):*
> ```XML
>   });
> 
>   it(' should have total/allocated of 35658/83200', async () => {
> ```

Maybe better: `it('should display the correct absolute completion', ...`
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 33 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhMESyEkMV2y62sdrg:-MbhMESyEkMV2y62sdrh:bg2f7xy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L33)):*
> ```XML
>   });
> 
>   it('should have completion of 42.9%', async () => {
> ```

Maybe better: `it('should display the correct relative completion', ...`
___
*[frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.ts, line 10 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhMZ3Y1z-PS-2-CwzZ:-MbhMZ3Y1z-PS-2-Cwz_:bw5carh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.ts#L10)):*
> ```XML
> })
> export class TimeAllocationTableComponent implements OnInit {
>   @Input() time_allocations!: TimeAllocation[];
> ```

time_allocations ---> time_allocation

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 38 of 59 files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/package.json, line 28 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhJlKC9OyHVmUtXadT:-Mbkag44CMHzb9-ZsVpN:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/package.json#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This version change looks really odd to me.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 19 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhKCd_89IlQB3paqB4:-Mbkavba2_Ocr_qma4u2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better `data-testid = "absolute-completion"`?
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.html, line 22 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhKbZO2cJoRrN5DmI9:-Mbkb9gx-x9YW8P-AVhb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.html#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better `data-testid="relative-completion"`?
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 2 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhL-cE3O1a1fO2dGGS:-MbkbHS1EQOZLDvcgdKm:bczfbml) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think importing the mock proposal is necessary - the component doesn't care where the time allocation / completion values come from. Also, it makes the tests more brittle (someone might change the mock data...) and harder to follow.
</blockquote></details>

are we not having this data for testing purposes
___
*[frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts, line 33 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhMESyEkMV2y62sdrg:-MbkbmVP8ENT4sDiZWde:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/charged-time-table/charged-time-table.component.spec.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: `it('should display the correct relative completion', ...`
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.ts, line 10 at r10](https://reviewable.io/reviews/saltastroops/web-manager-2021/21#-MbhMZ3Y1z-PS-2-CwzZ:-Mbjo13TCmWFvVYkksRR:bjo9cct) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/541138a18b19619a2cd59eef694ff4bd1b8bf3f0/frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

time_allocations ---> time_allocation
</blockquote></details>

it is allocations

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 4 files at r11, 6 of 8 files at r12, 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/21)* status: 36 of 59 files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
