### PR TITLE
hrs tables

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/app/types.ts, line 188 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF5jsY2cd95_6j9RK4:-MfF5jsY2cd95_6j9RK5:bbols0o) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L188)):*
> ```XML
> export interface HrsDetector {
>   readoutSpeed: ReadoutSpeed;
>   exposureTime: number
> ```

There is no exposureTime on this interface.
___
*[frontend/src/app/types.ts, line 219 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFAB62A2Zky0qaNTmJ:-MfFAB62A2Zky0qaNTmK:b-iuobeu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L219)):*
> ```XML
> export interface HrsProcedure {
>   cycles: number;
>   blueExposurePattern: number;
> ```

The exposure patterns are arrays of exposure times.
___
*[frontend/src/app/proposal/hrs/hrs-data.ts, line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF7SwZEVTqR19urFY5:-MfF7SwZEVTqR19urFY6:b-5ljo1g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/hrs-data.ts#L3)):*
> ```XML
> import {Hrs} from "../../types";
> 
> export const hrs: Hrs =
> ```

It might be better to have this file in the mock directory,
___
*[frontend/src/app/proposal/hrs/blue-detector-table/blue-detector-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF8nNq9R5JXuUyD6AV:-MfF8nNq9R5JXuUyD6AW:b2gf6ng) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/blue-detector-table/blue-detector-table.component.html#L1)):*
> ```HTML
> <div class="table alternate-background">
> ```

Given that the tables for the red and blue detector are the same really, it might make more sense to have a single component only (passing in the colour as an input).
___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF9BNd3W4I5JpyKB71:-MfF9BNd3W4I5JpyKB72:bi72qo7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L7)):*
> ```HTML
>   <div class="row headers configuration">
>     <div>Mode</div>
>     <div>Exposure Type	</div>
> ```

No need for whitespace before the closing div tags.
___
*[frontend/src/app/proposal/hrs/general-table/general-table.component.html, line 6 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBX7Q6gGjGklkFQUR:-MfFBX7Q6gGjGklkFQUS:b-xxf5jn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/general-table/general-table.component.html#L6)):*
> ```HTML
>   </div>
>   <div class="row  has-two-columns">
>     <div>MinSN</div><div></div>
> ```

There is no need for this column.
___
*[frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBcTR0DXUdjtEK8wB:-MfFBcTS0zVRBKJPUfe1:b-dmt60w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html#L9)):*
> ```HTML
>   </div>
>   <div class="row has-two-columns">
>     <div>Overheard</div><div>{{hrs.overhead}} sec</div>
> ```

Overheard ---> Overhead
___
*[frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html, line 12 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBfpdBmKy7y6uI-pV:-MfFBfpdBmKy7y6uI-pW:bxffrrl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html#L12)):*
> ```HTML
>   </div>
>   <div class="row has-two-columns">
>     <div>Charged	</div><div>{{hrs.charged}} sec</div>
> ```

No need for the whitespace before the closing div tag.
___
*[frontend/src/app/proposal/hrs/red-detector-table/red-detector-table.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBrdI-N01gO0jF7_L:-MfFBrdI-N01gO0jF7_M:bxffrrl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/red-detector-table/red-detector-table.component.html#L9)):*
> ```HTML
>   </div>
>   <div class="row has-two-columns">
>     <div>RoSpeed	</div><div>{{hrsRedDetector.readoutSpeed}}</div>
> ```

No need for the whitespace before the closing div tag.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: all files reviewed, 10 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfIBeUj3XRJWRmur7kK:-MfIBeUj3XRJWRmur7kL:b-7dccys) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L1)):*
> ```HTML
> <div class="table">
> ```

In view of what Nhlavu said at the meeting, it might be a good idea to rename all the HRS components to have "hrs" in its name.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: 14 of 33 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 188 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF5jsY2cd95_6j9RK4:-MfIPh8v7RJgbUiXQo-e:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no exposureTime on this interface.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 219 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFAB62A2Zky0qaNTmJ:-MfITlu8B9zzRae0vEfk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L219)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The exposure patterns are arrays of exposure times.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/hrs-data.ts, line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF7SwZEVTqR19urFY5:-MfITo0GAn9hnQMjZ6OX:b-7ruhe5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/hrs-data.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to have this file in the mock directory,
</blockquote></details>

For this, i have to create a service like it was done for proposal and block mock data?
___
*[frontend/src/app/proposal/hrs/blue-detector-table/blue-detector-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF8nNq9R5JXuUyD6AV:-MfITz_NBqqKSRwQAUbc:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/blue-detector-table/blue-detector-table.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that the tables for the red and blue detector are the same really, it might make more sense to have a single component only (passing in the colour as an input).
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfIBeUj3XRJWRmur7kK:-MfIU-mP2TNngtM3qmYN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In view of what Nhlavu said at the meeting, it might be a good idea to rename all the HRS components to have "hrs" in its name.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 7 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF9BNd3W4I5JpyKB71:-MfIU1TB-af1LmfYYOrI:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No need for whitespace before the closing div tags.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/general-table/general-table.component.html, line 6 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBX7Q6gGjGklkFQUR:-MfIU26fDc2BM12xcJdB:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/general-table/general-table.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is no need for this column.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBcTR0DXUdjtEK8wB:-MfIU7YCC0R2u9lxTSeY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Overheard ---> Overhead
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html, line 12 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBfpdBmKy7y6uI-pV:-MfIU72e7GLP_W-qUoBW:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/observing-times-table/observing-times-table.component.html#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No need for the whitespace before the closing div tag.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/red-detector-table/red-detector-table.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfFBrdI-N01gO0jF7_L:-MfIU99E4Xcw90z3_Uub:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/red-detector-table/red-detector-table.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No need for the whitespace before the closing div tag.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/app/types.ts, line 188 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF5jsY2cd95_6j9RK4:-MfJeMCp50dCWegtBSL6:b-cqsox7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L188)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, sorry, it seems I was clear as mud. My point was that HrsDetector has no exposureTime property. The exposure times are included in the HrsProcedure.
___
*[frontend/src/app/types.ts, line 221 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfJeik9088HrcWZ3xOM:-MfJeik9088HrcWZ3xON:baz3da8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4935c294884b5cb54369e06661605d3c4b0783cc/frontend/src/app/types.ts#L221)):*
> ```XML
> export interface HrsProcedure {
>   cycles: number;
>   blueExposurePattern: ExposureTime[];
> ```

Ib don't think there is a need for an ExposureTime interface; number[] would do.
___
*[frontend/src/app/proposal/hrs/hrs-data.ts, line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF7SwZEVTqR19urFY5:-MfJeu0X8Of_MFOJR6FX:b-qwbzg6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/hrs-data.ts#L3)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

For this, i have to create a service like it was done for proposal and block mock data?
</blockquote></details>

I'd suggest two fix this once there is live data available.
___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfIBeUj3XRJWRmur7kK:-MfJfa0a9mO2_Ykacih4:b-r5hnx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L1)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this... :-/

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: 22 of 29 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 188 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF5jsY2cd95_6j9RK4:-MfWj9s8DlLAZ_u3YjVN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/types.ts#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, sorry, it seems I was clear as mud. My point was that HrsDetector has no exposureTime property. The exposure times are included in the HrsProcedure.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 221 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfJeik9088HrcWZ3xOM:-MfJjavS0IyOoAIPXNhQ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4935c294884b5cb54369e06661605d3c4b0783cc/frontend/src/app/types.ts#L221)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ib don't think there is a need for an ExposureTime interface; number[] would do.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/hrs/hrs-data.ts, line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfF7SwZEVTqR19urFY5:-MfWim-00HhUQLDyxoep:b-ompgh3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/hrs-data.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest two fix this once there is live data available.
</blockquote></details>

I agree with you.
___
*[frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/58#-MfIBeUj3XRJWRmur7kK:-MfJi7sW63rIi61eqqUj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d77ae1baef0d471974c259942bb41d20dc0eca37/frontend/src/app/proposal/hrs/configuration-table/configuration-table.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see this... :-/
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 3 of 7 files at r4, 21 of 21 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
