### PR TITLE
salticam tables

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 16 of 26 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)* status: all files reviewed, 10 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 13 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Meiz5Lk1O-UEJsxHYgq:-Meiz5Lk1O-UEJsxHYgr:bt8gop0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L13)):*
> ```XML
> })
> export class SalticamComponent implements OnInit {
>   @Input() salticam: SalticamConfiguration = {
> ```

Please add a TODO that the initial value needs to be removed (or, even better, remove it). :-)

The same applies to all the other initial values for inputs.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 38 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej2Shf6Kl5mi-lXBsD:-Mej2Shf6Kl5mi-lXBsE:bn9hwdd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L38)):*
> ```XML
>   }
> 
>   @Input() observationTimes: ObservationTimes = {
> ```

This should be part of the Salticam configuration itself.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 44 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej3F0W74Nhg8Km_lQe:-Mej3F0X-NXZ8RMuMZwQ:bn9hwdd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L44)):*
> ```XML
>   }
> 
>   @Input() salticamFilterName: Filter = {
> ```

This should be part of the Salticam configuration itself.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 55 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MeiybHqDFzlp-gsvxm2:-MeiybHqDFzlp-gsvxm3:b-uxknxy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L55)):*
> ```XML
> }
> 
> interface SalticamFilterArray {
> ```

Why do you define the interfaces here rather than in types.ts (which in all fairness might need splitting up soon)?

Also, why is there a need for both a Salticam and a SalticamConfiguration type?

Why SalticamFilterArray rather than SalticamProcedure?
___
*[frontend/src/app/proposal/salticam/filters-table/filter-types.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej3i141bVugidtfwDy:-Mej3i141bVugidtfwDz:bgwl95m) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filter-types.ts#L1)):*
> ```XML
> enum Filters {
> ```

It might be better to include the required information in the object returned by the server.

We should chat about the question whether an enum should be used here, and whether there should be a separate filter-types.ts file.
___
*[frontend/src/app/proposal/salticam/filters-table/filter-types.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MejA-aCCiO7L4_zbw1R:-MejA-aCCiO7L4_zbw1S:bqvan76) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filter-types.ts#L31)):*
> ```XML
> 
> export interface ExposureTime {
>   units: string;
> ```

Explicitly using a units property introduces an inconsistency, as in other types values have no units. Also, you don't necessarily want to use whatever way the original XML thought the units should be spelled. So it might be better to modify whatever the server sends to have no value/unit.
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej7dTVBDK5K_RO5fFf:-Mej7dTVBDK5K_RO5fFg:bwvyab3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts#L9)):*
> ```XML
>   styleUrls: ['./filters-table.component.scss']
> })
> export class FiltersTableComponent implements OnInit {
> ```

You seem to assume that there is only a single filter. But there can be more than one.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times-type.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej80CG1pTmUtlsTDr0:-Mej80CG1pTmUtlsTDr1:b-hr1ytr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times-type.ts#L1)):*
> ```XML
> export interface ObservationTimes {
> ```

We should discuss whether there should be a file observation-times-type.ts.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts, line 12 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej8WC_9Hc4q4iRahqy:-Mej8WC_9Hc4q4iRahqz:b8qw3m0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts#L12)):*
> ```XML
> export class ObservationTimesComponent implements OnInit {
>   @Input() salticamComponent!: SalticamComponent;
>   @Input() observationTimes!: ObservationTimes;
> ```

The observation times should be part of the Salticam object...
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej8rXmDkldXTlT8hNW:-Mej8rXmDkldXTlT8hNX:bgiecdf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts#L17)):*
> ```XML
> 
>   ngOnInit(): void {
>     this.observationTimes = this.salticamComponent.observationTimes;
> ```

.... and it seems you agree. But then they shouldn't be declared as an input.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)* status: 15 of 27 files reviewed, 10 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 13 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Meiz5Lk1O-UEJsxHYgq:-MexJ3744FaskCtYvweH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Please add a TODO that the initial value needs to be removed (or, even better, remove it). :-)

The same applies to all the other initial values for inputs.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 38 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej2Shf6Kl5mi-lXBsD:-MexJ3lU1D4i1XLETVxf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be part of the Salticam configuration itself.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 44 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej3F0W74Nhg8Km_lQe:-MexJ4QN3kZgyBeRP3Fa:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be part of the Salticam configuration itself.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/salticam.component.ts, line 55 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MeiybHqDFzlp-gsvxm2:-MexJ2Ju9SKQLR4B9Ucy:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/salticam.component.ts#L55)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you define the interfaces here rather than in types.ts (which in all fairness might need splitting up soon)?

Also, why is there a need for both a Salticam and a SalticamConfiguration type?

Why SalticamFilterArray rather than SalticamProcedure?


</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej7dTVBDK5K_RO5fFf:-MexJ5UF1zK-02UZ_02U:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You seem to assume that there is only a single filter. But there can be more than one.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times-type.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej80CG1pTmUtlsTDr0:-MexJ61MDjEjL1ZHyQQz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times-type.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should discuss whether there should be a file observation-times-type.ts.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts, line 12 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej8WC_9Hc4q4iRahqy:-MexJ6Q-6sdZbp6xxuuO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The observation times should be part of the Salticam object...
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/filters-table/filter-types.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej3i141bVugidtfwDy:-MexJ8kj-cZYsGEeKCt5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filter-types.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to include the required information in the object returned by the server.

We should chat about the question whether an enum should be used here, and whether there should be a separate filter-types.ts file.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/filters-table/filter-types.ts, line 31 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MejA-aCCiO7L4_zbw1R:-MexJ9ur8hegzH-TDcKs:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/filters-table/filter-types.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Explicitly using a units property introduces an inconsistency, as in other types values have no units. Also, you don't necessarily want to use whatever way the original XML thought the units should be spelled. So it might be better to modify whatever the server sends to have no value/unit.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/app/types.ts, line 198 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezHvFLAfSRYDm5Usid:-MezHvFLAfSRYDm5Usie:bbtt2xw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/types.ts#L198)):*
> ```XML
> }
> 
> export interface SalticamFilterArray {
> ```

The name (taken from the JSON?) is unfortunate, as this is not an array, but a single filter setup.

But we should discuss the types at the meeting tomorrow.
___
*[frontend/src/app/proposal/salticam/detector-table/detector-table.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezF1PEBAEF3wlVGh1Q:-MezF1PEBAEF3wlVGh1R:b-iwz0lc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/detector-table/detector-table.component.ts#L10)):*
> ```XML
> })
> export class DetectorTableComponent implements OnInit {
>   @Input() salticam!: Salticam;
> ```

Why do you pass a Salticam rather than a SalticamDetector?
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.html, line 6 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezEyIU9xQpDd6Zd1SE:-MezEyIU9xQpDd6Zd1SF:b-ps2ctz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.html#L6)):*
> ```HTML
>   </div>
>   <div class="row headers filters">
>     <div>Name: </div>
> ```

I wouldn't use colons here.
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.html, line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezEM_m04I6PxFc-G4b:-MezEM_n7e5j2hqdkDyC:bqejo6f) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.html#L15)):*
> ```HTML
>       <div>{{f.exposureTime}} sec</div>
>   </div>
>   <div class="row filters-row">
> ```

This obviously should only be shown if the filter is unavailable. Also, it wouldn't be clear which of filters are unavailable. :-) 
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezHMZ2-zhqJMmKNxn8:-MezHMZ3AqHssUOAq8Ud:be4bf9z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts#L10)):*
> ```XML
> })
> export class FiltersTableComponent implements OnInit {
>   @Input() salticam!: Salticam;
> ```

We should agree at the meeting tomorrow whether generally to pass an instrument object or, say, the procedure, detector, ...
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.html, line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezFQXK1MZqRdRh6NM5:-MezFQXK1MZqRdRh6NM6:b-dmt60w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/observation-times/observation-times.component.html#L9)):*
> ```HTML
>   </div>
>   <div class="row has-two-columns">
>     <div>Overheard</div><div>{{salticam.overhead}} sec</div>
> ```

Overheard ---> Overhead

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/types.ts, line 198 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezHvFLAfSRYDm5Usid:-MezbXyv8x0IlBP7KIJ8:b-pbcqkp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/types.ts#L198)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name (taken from the JSON?) is unfortunate, as this is not an array, but a single filter setup.

But we should discuss the types at the meeting tomorrow.
</blockquote></details>

You're right I took this from the JSON file. I have changed to SalticamFilter now
___
*[frontend/src/app/proposal/salticam/detector-table/detector-table.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezF1PEBAEF3wlVGh1Q:-MezbIFd-qTm9mtj5eA7:b-i0kapn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/detector-table/detector-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you pass a Salticam rather than a SalticamDetector?
</blockquote></details>

I change it to SalticamDetector for now
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.html, line 6 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezEyIU9xQpDd6Zd1SE:-MezYG2a3TXDI5n0N2pC:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I wouldn't use colons here.
</blockquote></details>

Removed.
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.html, line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezEM_m04I6PxFc-G4b:-MezXN4aA6GYR7TaO637:bvdvuet) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.html#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This obviously should only be shown if the filter is unavailable. Also, it wouldn't be clear which of filters are unavailable. :-) 
</blockquote></details>

I see what you mean, I was not sure whether to add another property, say the status.
Is that what I should do, add a status property to SalticamFilter? 
___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts, line 10 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezHMZ2-zhqJMmKNxn8:-MezYNiqA6feBS8Z0th-:btab27g) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should agree at the meeting tomorrow whether generally to pass an instrument object or, say, the procedure, detector, ...
</blockquote></details>

I was doing this because I wasn't sure how data gets passed around to different components. But I am going to change this for now and i will change again if need be after our meeting tomorrow.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.html, line 9 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezFQXK1MZqRdRh6NM5:-MezZL3K9u4vNgHLCp4Q:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/observation-times/observation-times.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Overheard ---> Overhead
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-Mej8rXmDkldXTlT8hNW:-MexK1Wq9VTMPkGDeeRQ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/4e13d84630a711245974c8b8c27ed8726e73d782/frontend/src/app/proposal/salticam/observation-times/observation-times.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

.... and it seems you agree. But then they shouldn't be declared as an input.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/51)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/app/proposal/salticam/filters-table/filters-table.component.html, line 15 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/51#-MezEM_m04I6PxFc-G4b:-MeznJP0Crr1xv8VREuU:bdrxwmd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/11f60121ec30385d25b44c32dffe456661552f85/frontend/src/app/proposal/salticam/filters-table/filters-table.component.html#L15)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I see what you mean, I was not sure whether to add another property, say the status.
Is that what I should do, add a status property to SalticamFilter? 
</blockquote></details>

Let's discuss this tomorrow.

**Pull request merged**
