### PR TITLE
added new hashing algorithm

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 8 unresolved discussions (waiting on @mofokeng-chaka)

___
*[python/app/dependencies.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Mcy_HKUEakoVbG2F0IZ:-Mcy_HKUEakoVbG2F0I_:busjint) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/dependencies.py#L8)):*
> ```Python
> from fastapi import Depends, HTTPException
> #from jose import JWTError, jwt
> import jwt
> ```

Is there a reason why you replaced jose with pyjwt?
___
*[python/app/routers/auth.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyQXYb7W5wFBX9-QT4:-McyQXYc25zsooD3opn4:b3r992u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/routers/auth.py#L34)):*
> ```Python
>     curl -H "Authorization: Bearer abcd1234" /api/some/secret/resource
>     ```
> a
> ```

This "a" seems to be an error. :-)
___
*[python/app/routers/auth.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyQl9m3-Kxv1AJq4Lu:-McyQl9nExFHFoypuXPS:bpmd5tc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/routers/auth.py#L48)):*
> ```Python
>             headers={"WWW-Authenticate": "Bearer"},
>         )
>     new_password_hash = authentication.get_new_password_hash(form_data.password)
> ```

This function is not the ideal place for creating the new hash -- most people might never use. It might be better to create the token when checking the password.

You might also consider what (and why) you are doing here. :-)
___
*[python/app/service/user.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McxRH_51bEty7QHBt57:-McxRH_51bEty7QHBt58:brcx8k9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L34)):*
> ```Python
>             )
> 
> async def get_new_hash(username: str, password: str, db: Pool) -> UserInDB:
> ```

The name is unfortunate, as you are not getting the hash, but updating it. Maybe call the function something like update_password_hash. Also, you might consider passing in the password and hashing it within the function, which might make it slightly safer.
___
*[python/app/service/user.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyS1150IGGWLbVDASi:-McyS1150IGGWLbVDASj:bcbvef5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L36)):*
> ```Python
> async def get_new_hash(username: str, password: str, db: Pool) -> UserInDB:
>     sql = """
> UPDATE temp_password t
> ```

I would suggest you use INSERT ... UPDATE IF EXISTS ... instead, as the user might not be in your temp_password table yet.

And as the table is not that temporary, maybe avoid the temp_ prefix.
___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyTVuQBkJADaTnk_1a:-McyTVuQBkJADaTnk_1b:bk9g6kj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L44)):*
> ```Python
>             await cur.execute(sql, {"username": username, "password": password})
>             r = await cur.fetchall()
>             if r is None:
> ```

I'm not sure what fetchall() returns for an UPDATE, but it is either always or never `None`.
___
*[python/app/util/authentication.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyVZu34NYhJGRim-GB:-McyVZu34NYhJGRim-GC:busjint) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/util/authentication.py#L17)):*
> ```Python
> from fastapi.security.utils import get_authorization_scheme_param
> #from jose import jwt
> import jwt
> ```

Is there a reason why you replaced jose with pyjwt?
___
*[python/app/util/authentication.py, line 72 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyWN5iCLoucdmHH2zb:-McyWN5iCLoucdmHH2zc:bz7a4sz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/util/authentication.py#L72)):*
> ```Python
> def verify_password(password: str, hashed_password: str) -> bool:
>     """Check a plain text password against a hash."""
>     return get_password_hash(password) == hashed_password
> ```

This line constitutes a security loophole, as it opens the gate to timing attacks.(I'm happy to explain. :) ) 

The verify method of pwd_context should be used instead. (You'll have to add md5 to the schemes parameter array when creating the context:\

```pwd_context = CryptContext(schemes=["bcrypt", "md5"], default="bcrypt", deprecated="auto")```

And, yes, I know you didn't write this line. :-)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[python/app/dependencies.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Mcy_HKUEakoVbG2F0IZ:-Md1UFXX4RvaE0aG9bRq:b-yijxd2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/dependencies.py#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you replaced jose with pyjwt?
</blockquote></details>

it was just for convenience; to be able to run the code on my computer. I had a problem because I forgot the path to a virtual environment created by poetry, so I installed some of the libraries I didn't have already on my computer. For some reason, I couldn't find jose but I found that pyjwt has the functions we require, and I used it instead. Consider this fixed.
___
*[python/app/routers/auth.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyQXYb7W5wFBX9-QT4:-Md1YMFZ280AznKAKWvS:b-p1etpp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/routers/auth.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This "a" seems to be an error. :-)
</blockquote></details>

My mistake, I did not see this. Thanks!
___
*[python/app/routers/auth.py, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyQl9m3-Kxv1AJq4Lu:-Md1YfpPBovKUEz1b_p0:bcku6vz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/routers/auth.py#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This function is not the ideal place for creating the new hash -- most people might never use. It might be better to create the token when checking the password.

You might also consider what (and why) you are doing here. :-)
</blockquote></details>

I see what you mean, I removed this function bit and put it in after checking the password.
___
*[python/app/service/user.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McxRH_51bEty7QHBt57:-Md1ZbZ3Df_pGMNM2vtV:bvwy029) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name is unfortunate, as you are not getting the hash, but updating it. Maybe call the function something like update_password_hash. Also, you might consider passing in the password and hashing it within the function, which might make it slightly safer.
</blockquote></details>

I agree and have updated the name of the function. Just one question before I commit changes, because I am not return anything from this function, I can remove "-> UserInDB"?
___
*[python/app/service/user.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyS1150IGGWLbVDASi:-Md1a7HA3jm1enIAJ45K:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest you use INSERT ... UPDATE IF EXISTS ... instead, as the user might not be in your temp_password table yet.

And as the table is not that temporary, maybe avoid the temp_ prefix.
</blockquote></details>

Done.
___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyTVuQBkJADaTnk_1a:-Md1aG-w0JPoHloMrTXS:b-oukq19) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure what fetchall() returns for an UPDATE, but it is either always or never `None`.
</blockquote></details>

The problem is that fetchone() and fetchmany() retrieves the next row and next set of rows respectively and I happened to be using the last user in the table, so they will always return none because there aren't next rows in the table, even if the query ran successfully. I ended up using fetchall().
___
*[python/app/util/authentication.py, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyVZu34NYhJGRim-GB:-Md1bYaxEtnOEIeQvU_w:bq8vd7z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/util/authentication.py#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you replaced jose with pyjwt?
</blockquote></details>

I have addressed this in my reply to your first comment.
___
*[python/app/util/authentication.py, line 72 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyWN5iCLoucdmHH2zb:-Md1bQBe8rH1Om6V5HRS:b7klxtt) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/util/authentication.py#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line constitutes a security loophole, as it opens the gate to timing attacks.(I'm happy to explain. :) ) 

The verify method of pwd_context should be used instead. (You'll have to add md5 to the schemes parameter array when creating the context:\

```pwd_context = CryptContext(schemes=["bcrypt", "md5"], default="bcrypt", deprecated="auto")```

And, yes, I know you didn't write this line. :-)
</blockquote></details>

I have read a bit about timing attacks and the use of salt strings as a solution for this. So I have added the above line to the code.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[python/app/dependencies.py, line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Mcy_HKUEakoVbG2F0IZ:-Md2A7ID9p-eKQoVVn2w:b-8xrp7y) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/dependencies.py#L8)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

it was just for convenience; to be able to run the code on my computer. I had a problem because I forgot the path to a virtual environment created by poetry, so I installed some of the libraries I didn't have already on my computer. For some reason, I couldn't find jose but I found that pyjwt has the functions we require, and I used it instead. Consider this fixed.
</blockquote></details>

You might be interested to know that you can configure poetry to put your virtual environment directory within your project folder:

https://python-poetry.org/docs/configuration/#virtualenvsin-project

I personally prefer this a lot. Just make sure it doesn't end up in git... :-)
___
*[python/app/service/user.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McxRH_51bEty7QHBt57:-Md2D35GBvxEb9kNnPSE:btd3ekr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L34)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I agree and have updated the name of the function. Just one question before I commit changes, because I am not return anything from this function, I can remove "-> UserInDB"?
</blockquote></details>

You even have to -- otherwise mypy will yell at you. :-)

As mypy is run in strict mode, you still need a return type, though; you have to use `-> None`.
___
*[python/app/service/user.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyS1150IGGWLbVDASi:-Md2B_XS9ILpX4vIwX-9:b6yur7n) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L36)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I know this is nitpicking, but the table names in the SDB generally are singular, not plural.
___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyTVuQBkJADaTnk_1a:-Md2CCEq-uzui_gHBLlm:b-4zreu5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L44)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The problem is that fetchone() and fetchmany() retrieves the next row and next set of rows respectively and I happened to be using the last user in the table, so they will always return none because there aren't next rows in the table, even if the query ran successfully. I ended up using fetchall().
</blockquote></details>

It is a bit puzzling if it matters whether the user is in the last row or not... But maybe you cannot fetch the result of an UPDATE (which should be true or false?).

At any rate, now that you are using an INSERT, there is no need for this check any more.
___
*[python/app/service/user.py, line 47 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Md2Dbbv6PdqOY3BVVOe:-Md2Dbbv6PdqOY3BVVOf:b-oaoauf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9fc352c74d9902f0f706ce03b5a8cacf2d00cfa5/python/app/service/user.py#L47)):*
> ```Python
>             await cur.execute(sql, {"username": username, "password": new_password_hash})
>             r = await cur.fetchall()
>             print(r)
> ```

The print statement should be removed. :)
___
*[python/app/util/authentication.py, line 72 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyWN5iCLoucdmHH2zb:-Md2Dwc_6iBW9AfLGzH-:b-ucfknh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/util/authentication.py#L72)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have read a bit about timing attacks and the use of salt strings as a solution for this. So I have added the above line to the code.
</blockquote></details>

Thanks!
___
*[python/app/util/authentication.py, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Md2E4603kCBTwDKhkyQ:-Md2E461DIBBYJguefYT:b-sgk5b2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9fc352c74d9902f0f706ce03b5a8cacf2d00cfa5/python/app/util/authentication.py#L96)):*
> ```Python
>         return None
> 
>     update_user_password = await user_service.update_password_hash(username, password, db)
> ```

The `update_user_password =` is unnecessary. :-)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[python/app/service/user.py, line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McxRH_51bEty7QHBt57:-Md2GBGw2gSiuA_hM8eY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You even have to -- otherwise mypy will yell at you. :-)

As mypy is run in strict mode, you still need a return type, though; you have to use `-> None`.
</blockquote></details>

Done.
___
*[python/app/service/user.py, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyS1150IGGWLbVDASi:-Md2GDJTB_LzLZPHoJ2g:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I know this is nitpicking, but the table names in the SDB generally are singular, not plural.
</blockquote></details>

Done.
___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyTVuQBkJADaTnk_1a:-Md2H_1H5S-hMF2LWY_i:b-8wnati) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It is a bit puzzling if it matters whether the user is in the last row or not... But maybe you cannot fetch the result of an UPDATE (which should be true or false?).

At any rate, now that you are using an INSERT, there is no need for this check any more.
</blockquote></details>

I have pasted a typical output from the UPDATE command below:

Query OK, 1 row affected (0.03 sec)
Rows matched: 1  Changed: 1  Warnings: 0

Apparently, that is the only type of output one will get from this command, even if there's no record that was updated. So I will remove the fetchall() line as well.
___
*[python/app/service/user.py, line 47 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Md2Dbbv6PdqOY3BVVOe:-Md2GH06EWNyuWyRJVN-:b-shiynk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9fc352c74d9902f0f706ce03b5a8cacf2d00cfa5/python/app/service/user.py#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The print statement should be removed. :)
</blockquote></details>

Oh, i forgot to remove it. Thanks!
___
*[python/app/util/authentication.py, line 96 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-Md2E4603kCBTwDKhkyQ:-Md2IxpSEGTkmB9Lhk7g:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/9fc352c74d9902f0f706ce03b5a8cacf2d00cfa5/python/app/util/authentication.py#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The `update_user_password =` is unnecessary. :-)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[python/app/service/user.py, line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/40#-McyTVuQBkJADaTnk_1a:-Md2bjnrE1NA-50YOo2K:b-m3kdbl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f3743680adeac33f4711217b0bba7abe54e38fd4/python/app/service/user.py#L44)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have pasted a typical output from the UPDATE command below:

Query OK, 1 row affected (0.03 sec)
Rows matched: 1  Changed: 1  Warnings: 0

Apparently, that is the only type of output one will get from this command, even if there's no record that was updated. So I will remove the fetchall() line as well.
</blockquote></details>

Just for the sake of interest: If you wanted to find out the number of rows updated, you probably could use `cursor.rowcount`.

**Review by hettlage — COMMENTED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/40)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Pull request merged**
