### PR TITLE
Check PI/PC with user id issue fix

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[src/app/home/home-user/home-user.component.ts, line 304 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL12Tr8YtPvKrd1KMP:-MzL12Tr8YtPvKrd1KMQ:bx9d3vb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/home/home-user/home-user.component.ts#L304)):*
> ```XML
> 
>   filterMyProposals = (proposals: ProposalListItem[]): ProposalListItem[] => {
>     proposals.map((p) =>
> ```

Unnecessary statement (and you'd use `forEach` rather than `map`:) ),
___
*[src/app/types/proposal.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL2_RK39Ooj25RVi-H:-MzL2_RK39Ooj25RVi-I:b-wjtr3m) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/types/proposal.ts#L21)):*
> ```XML
> 
> export interface ContactDetails {
>   id: number;
> ```

What troubles me a bit is that having the id in `ContactDetails` is a bit misleading, as the id is not for contact details. So maybe you need another type, say `ProposalUser`, which extends `ContactDetails` and contains the id. The `Investigator` type then might extend `ProposalUser` as well.
___
*[src/app/types/proposal.ts, line 46 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL3JhB0tndPcGnRLHC:-MzL3JhB0tndPcGnRLHD:b-otilcs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/types/proposal.ts#L46)):*
> ```XML
> 
> export interface Investigator {
>   id: number;
> ```

See comment above.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/app/home/home-user/home-user.component.ts, line 304 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL12Tr8YtPvKrd1KMP:-MzOFXyb7lX8JvcjqJSA:b-vym8wo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/home/home-user/home-user.component.ts#L304)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary statement (and you'd use `forEach` rather than `map`:) ),
</blockquote></details>

Thanks, I forgot to remove it.
___
*[src/app/types/proposal.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL2_RK39Ooj25RVi-H:-MzTRsy46cz7ysFolUP6:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/types/proposal.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What troubles me a bit is that having the id in `ContactDetails` is a bit misleading, as the id is not for contact details. So maybe you need another type, say `ProposalUser`, which extends `ContactDetails` and contains the id. The `Investigator` type then might extend `ProposalUser` as well.
</blockquote></details>

Done.
___
*[src/app/types/proposal.ts, line 46 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzL3JhB0tndPcGnRLHC:-MzTRtyP6MJw-yTskaYx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/98a8f24aa50cc381fae14cc28a08d8aa021cd801/src/app/types/proposal.ts#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[src/app/home/home-user/home-user.component.ts, line 78 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzTs0S6DQSFILr2KR_w:-MzTs0S77InKP1AqPSIf:bnie0nk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f9474729c2289c95ae736d7173aea9c645ba3d37/src/app/home/home-user/home-user.component.ts#L78)):*
> ```XML
>     this.authService.getUser().subscribe((user: User) => {
>       this.user = user;
>       console.log(user);
> ```

Unnecessary console.log.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/app/home/home-user/home-user.component.ts, line 78 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/107#-MzTs0S6DQSFILr2KR_w:-MzU6-C-DAIBq5HPu9-9:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f9474729c2289c95ae736d7173aea9c645ba3d37/src/app/home/home-user/home-user.component.ts#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary console.log.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
