### PR TITLE
Displaying block content

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 30 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: 30 of 53 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[frontend/src/app/types/proposal.ts, line 57 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgiUYEQBNKwo7MNN9Nn:-MgiUYEQBNKwo7MNN9No:b5266el) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/types/proposal.ts#L57)):*
> ```XML
>   author: string;
>   comment: string;
>   commentDate: string;
> ```

Type error, the backend type is datetime.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: 30 of 53 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[frontend/src/app/types/proposal.ts, line 57 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgiUYEQBNKwo7MNN9Nn:-MgixjQh9cz3100XWN_m:bnyby3e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/types/proposal.ts#L57)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Type error, the backend type is datetime.
</blockquote></details>

Well spotted, but this isn't a type error. The trouble is that all these types must cater for objects that are created from JSON, and JSON doesn't have a datetime type.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 23 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/app/proposal/blocks/block/observation/observation.component.html, line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnT7WX-seX0-j1oBGj:-MgnT7WX-seX0-j1oBGk:b-p3f6w1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/proposal/blocks/block/observation/observation.component.html#L23)):*
> ```HTML
>   </div>
>   <div class="row payload-table-row">
>     <div>n/a</div>
> ```

why dispaly value that will always be n/a
___
*[frontend/src/app/proposal/blocks/block/observation/observation.component.html, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnTPja4y6xxSXe6m7g:-MgnTPja4y6xxSXe6m7h:bpl3tbm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/proposal/blocks/block/observation/observation.component.html#L50)):*
> ```HTML
>       <div>
>                    src="/assets/noun_Night_771441.png"
> ```

needs to be discusses that this be fixed
___
*[frontend/src/app/service/real/real-block.service.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnUiaeBmI5gYm8-E_b:-MgnUiafCzYAXyCB-aFi:bko446t) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/service/real/real-block.service.ts#L28)):*
> ```XML
>       map((block: Block) => camelcaseKeys(block, { deep: true })),
>       catchError(() => {
>         return throwError('The request has failed.');
> ```

There is a problem with this error message.
it feels like error is happening somewhere else

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[frontend/src/app/proposal/blocks/block/observation/observation.component.html, line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnT7WX-seX0-j1oBGj:-MgqlvWFB4JbJYwFgBW8:b-5yx9dr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/proposal/blocks/block/observation/observation.component.html#L23)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

why dispaly value that will always be n/a
</blockquote></details>

For the simple reason that this still needs to be implemented...
___
*[frontend/src/app/proposal/blocks/block/observation/observation.component.html, line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnTPja4y6xxSXe6m7g:-Mgqm7c60xfBwZAkIvUf:bnc5se1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/proposal/blocks/block/observation/observation.component.html#L50)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

needs to be discusses that this be fixed
</blockquote></details>

Yes, once there is an endpoint for it. :-)
___
*[frontend/src/app/service/real/real-block.service.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnUiaeBmI5gYm8-E_b:-Mgqlhmu8bX5nUqWKyDV:b-gzd7l0) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/service/real/real-block.service.ts#L28)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

There is a problem with this error message.
it feels like error is happening somewhere else
</blockquote></details>

I'm not averse to changing the error message. Maybe something like "Ops. Something is wrong."?

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[frontend/src/app/service/real/real-block.service.ts, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/74#-MgnUiaeBmI5gYm8-E_b:-MhNhrPQ3MxFNF769Rnm:b-mridmx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/e760fb0bae520a0cc53eda0ec58276774c6dfcc5/frontend/src/app/service/real/real-block.service.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not averse to changing the error message. Maybe something like "Ops. Something is wrong."?
</blockquote></details>

The problem is you will never knw what went wrong.
and this message is not displayed to the user is for us developers.
errors for user should be handle better

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
