### PR TITLE
bvit tables

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/bvit-tables/bvit-data.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7TK4zEPaA-6EZgEqa:-Mf7TK4zEPaA-6EZgEqb:br149bk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-data.ts#L2)):*
> ```XML
> import {Bvit} from "../../types";
> ```

As this is mock data, I'd suggest to move the file to the mock folder (or to add a TODO that it needs to be removed).
___
*[frontend/src/app/proposal/bvit-tables/bvit-tables.component.html, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7Tg3X3nNSo686_7wJ:-Mf7Tg3YCX-Tb5LZkZ6c:b-xb2139) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-tables.component.html#L5)):*
> ```HTML
> <div class="bvit">
>   <div>
>     <wm-general-table [bvitGeneralDetails]="bvit"></wm-general-table>
> ```

"bvit-tables" probably should just be "bvit".

Also, I'm not convinced you need two components for BVIT.
___
*[frontend/src/app/proposal/bvit-tables/general-table/general-table.component.html, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7U-s4AGs4F80i90Ns:-Mf7U-s4AGs4F80i90Nt:b-4yvcsm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/general-table/general-table.component.html#L7)):*
> ```HTML
>   <div class="row headers general">
>     <div>Mode</div>
>     <div>Iris size	</div>
> ```

You might consider removing the white space before the closing div in this and the next lines.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)* status: 3 of 14 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/proposal/bvit-tables/bvit-tables.component.html, line 5 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7Tg3X3nNSo686_7wJ:-Mf7gws1-dYOHy12sdJR:b-46ue7i) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-tables.component.html#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"bvit-tables" probably should just be "bvit".

Also, I'm not convinced you need two components for BVIT.
</blockquote></details>

Removed the general-table component
___
*[frontend/src/app/proposal/bvit-tables/general-table/general-table.component.html, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7U-s4AGs4F80i90Ns:-Mf7hAoq6x7kzY7szl8F:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/general-table/general-table.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider removing the white space before the closing div in this and the next lines.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/bvit-tables/bvit-data.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-Mf7TK4zEPaA-6EZgEqa:-Mf7guZ-46UkE1osyMtl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-data.ts#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As this is mock data, I'd suggest to move the file to the mock folder (or to add a TODO that it needs to be removed).
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/bvit-tables/bvit-tables.component.ts, line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-MfF3CRWCw1SG-ZSuc0l:-MfF3CRXClRoX88spkVk:b-mt4gxz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-tables.component.ts#L6)):*
> ```XML
> @Component({
>   selector: 'wm-bvit-tables',
>   templateUrl: './bvit-tables.component.html',
> ```

The file BVIT.component.html is missing.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/bvit-tables/bvit-tables.component.ts, line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/57#-MfF3CRWCw1SG-ZSuc0l:-MfF3CRXClRoX88spkVk:b-mt4gxz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/68c5c82446db6205e8b7740755851540a6b53ef0/frontend/src/app/proposal/bvit-tables/bvit-tables.component.ts#L6)):*
> ```XML
> @Component({
>   selector: 'wm-bvit-tables',
>   templateUrl: './bvit-tables.component.html',
> ```

The file BVIT.component.html is missing.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/57)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Pull request merged**
