### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 15 of 26 files at r1, 22 of 23 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)* status: 37 of 38 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[docs/api.md, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTnugpV0kMoDm3RIejZ:-MTnugpV0kMoDm3RIej_:bctb240) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/api.md#L8)):*
> ```Markdown
> 
> ```shell
> curl -X POST -F "username=john" -F "password=doe" /api/token
> ```

Are you not missing the host
___
*[docs/api.md, line 19 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTnvHDAEPdnb4ZirFF3:-MTnvHDAEPdnb4ZirFF4:bgrb0j6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/api.md#L19)):*
> ```Markdown
> 
> ```shell
> curl -H "Authorization: Bearer abcd1234" /api/secret/resource
> ```

most likey or alwway you would need to provide some extra parameters in what format would they the provided?
___
*[docs/development.md, line 127 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTo-rcT0BQH1EK88sZk:-MTo-rcT0BQH1EK88sZl:bh07a7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/development.md#L127)):*
> ```Markdown
> 
> !!! note
> In particular the pre-commit hook is _not_ effective, as it formats _all_ files, not just the committed ones. Also, it does not commit any reformatted code; so after the commit you may have new changes to commit...
> ```

Now that this is back again.
Does it mean that the comminted file will be modified for the next commit ?
___
*[python/mypy.ini, line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTo2Z1wELgZ5B3Ws3ia:-MTo2Z1wELgZ5B3Ws3ib:b-az0w3h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/mypy.ini#L6)):*
> ```INI
> 
> [mypy-jose.*]
> ignore_missing_imports = True
> ```

why ignore missing imports
___
*[python/app/service/user.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToI6ux-e9CUF57Mc67:-MToI6ux-e9CUF57Mc68:b92sews) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/service/user.py#L8)):*
> ```Python
> def get_user(username: str) -> UserInDB:
>     return UserInDB(
>         username=username, hashed_password=auth.get_password_hash("!" + username)
> ```

you still have this here thougth we will use MD5 since it is still used in SDB
___
*[python/app/util/auth.py, line 77 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToYFm41AYzCIxmV1gS:-MToYFm5-mbEc8mehC9w:b-swclow) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/util/auth.py#L77)):*
> ```Python
> 
> 
> def get_password_hash(password: str) -> str:
> ```

this method is no longer valid
___
*[python/app/util/auth.py, line 105 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToY_eO3qJPHon-LyJn:-MToY_ePCVf7hqZyBf2k:b-wlbgxy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/util/auth.py#L105)):*
> ```Python
>         expire = datetime.utcnow() + expires_delta
>     else:
>         expire = datetime.utcnow() + timedelta(minutes=15)
> ```

why do we need a 15 miutes token?

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)* status: 31 of 38 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[docs/api.md, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTnugpV0kMoDm3RIejZ:-MUDfdxa5_-mLqsncvCz:bqmjwcz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/api.md#L8)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Are you not missing the host
</blockquote></details>

Added.
___
*[docs/api.md, line 19 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTnvHDAEPdnb4ZirFF3:-MUDfg7Q4fyNCkX-z4Bq:bsq2izn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/api.md#L19)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

most likey or alwway you would need to provide some extra parameters in what format would they the provided?
</blockquote></details>

As discussed, no.
___
*[docs/development.md, line 127 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTo-rcT0BQH1EK88sZk:-MUDfjfW8qEWGWrnx5ay:b-wy3hv3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/docs/development.md#L127)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Now that this is back again.
Does it mean that the comminted file will be modified for the next commit ?
</blockquote></details>

As discussed, yes.
___
*[python/mypy.ini, line 6 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MTo2Z1wELgZ5B3Ws3ia:-MUDfmh45fyuaHsBKurk:b-w3va6s) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/mypy.ini#L6)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

why ignore missing imports
</blockquote></details>

As discussed, to keep my sanity.
___
*[python/app/service/user.py, line 8 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToI6ux-e9CUF57Mc67:-MUDft2h1v5PkmODQqXs:b-a83h1y) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/service/user.py#L8)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

you still have this here thougth we will use MD5 since it is still used in SDB
</blockquote></details>

As discussed, the hashing method will change.
___
*[python/app/util/auth.py, line 77 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToYFm41AYzCIxmV1gS:-MUDg0kZA7xcfq-ee0sm:buha8ym) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/util/auth.py#L77)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this method is no longer valid
</blockquote></details>

As discussed, it still is relevant.
___
*[python/app/util/auth.py, line 105 at r3](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MToY_eO3qJPHon-LyJn:-MUDg5J26VaO0MOtgfCK:bf4e81j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ce94088245b2bea75245ccd21a996544d9e68614/python/app/util/auth.py#L105)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

why do we need a 15 miutes token?
</blockquote></details>

Changed to 1 week.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 23 files at r3, 29 of 32 files at r4, 18 of 20 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)* status: 54 of 56 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[docs/development.md, line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MVQ4QXtCreXgTFWJRxJ:-MVQ4QXtCreXgTFWJRxK:b-kg6j04) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f8d8fc432d4133e518d1fad58aec16030e680845/docs/development.md#L51)):*
> ```Markdown
> 
> !!! note
> The .env file is also read for the unit tests, unless its environment variables are defined elsewhere as well. The `conftest.py` file therefore contains a fixture which explicitly defines all these variables and sets their value to an empty string.
> ```

don't we need somethng like .env.test for test env
___
*[python/app/routers/api.py, line 52 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MVFofX35WXtSklv1JiT:-MVFofX35WXtSklv1JiU:bxfrsb8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/87eb367ced683b01aa644cefaf7fcc7722079f4b/python/app/routers/api.py#L52)):*
> ```Python
> 
> 
> @router.get("/api/proposals/{proposal_code}/blocks/{block_code}")
> ```

url should specify that the block is html somewhere in the url
___
*[python/tests/test_dependencies.py, line 77 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MVQF9ep5S45Ih7R3Rl4:-MVQF9ep5S45Ih7R3Rl5:b-o7k1bd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f8d8fc432d4133e518d1fad58aec16030e680845/python/tests/test_dependencies.py#L77)):*
> ```Python
>     assert excinfo.value.status_code == 401
> ```

I believe our token expires as well.
that need to be tested too.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)* status: 54 of 56 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[docs/development.md, line 51 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MVQ4QXtCreXgTFWJRxJ:-MVQapna9qcTrusQ3g-g:b-ovwaw7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/f8d8fc432d4133e518d1fad58aec16030e680845/docs/development.md#L51)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

don't we need somethng like .env.test for test env
</blockquote></details>

Good idea.
___
*[python/app/routers/api.py, line 52 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/4#-MVFofX35WXtSklv1JiT:-MVQbfBeERwPJbkksQ5I:bh2mgj7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/87eb367ced683b01aa644cefaf7fcc7722079f4b/python/app/routers/api.py#L52)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

url should specify that the block is html somewhere in the url
</blockquote></details>

Won't fix

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 20 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
