### PR TITLE
General table

### PR DESCRIPTION
**Pull request by saltastroops**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1, 2 of 5 files at r2, 2 of 12 files at r3, 11 of 19 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 12 unresolved discussions (waiting on @saltastroops)

___
*[frontend/tsconfig.json, line 26 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3HesQDRU7hVvfBd39:-Ma3HesQDRU7hVvfBd3A:b-kn1c98) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/tsconfig.json#L26)):*
> ```jsonc
>     "strictInputAccessModifiers": true,
>     "strictTemplates": true,
>     "enableIvy": false
> ```

Why does this have to be false?
___
*[frontend/src/styles.scss, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JOlNEPBe0xtK3x3f:-Ma3JOlNEPBe0xtK3x3g:b-5g47v1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d9341aaa8f2260f4e96fece21d654039e8dbf533/frontend/src/styles.scss#L21)):*
> ```SCSS
> }
> 
> .table {
> ```

Styling needs discussion, regarding:

- background colour
- font size
___
*[frontend/src/app/types.ts, line 16 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3Jccg9ZcJ2I4UImD7:-Ma3Jcch8zquqFbympAI:bhtlbx4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L16)):*
> ```XML
> }
> 
> export interface General {
> ```

The name is too generic.
___
*[frontend/src/app/types.ts, line 21 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JpauAvllp3TcXGUs:-Ma3JpauAvllp3TcXGUt:b-b1j0op) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L21)):*
> ```XML
>   title: string,
>   abstract: string,
>   current_submission: Date,
> ```

The submission number is missing.
___
*[frontend/src/app/types.ts, line 24 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JxyiA2tpeWXzccQa:-Ma3JxyiA2tpeWXzccQb:bk709d2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L24)):*
> ```XML
>   first_submission: Date,
>   phase: number,
>   semesters: Semester[],
> ```

This needs discussion.
___
*[frontend/src/app/types.ts, line 33 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JjBn6xsF_jRjduH6:-Ma3JjBn6xsF_jRjduH7:bhtlbx4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L33)):*
> ```XML
> }
> 
> interface Status {
> ```

The name is too generic.
___
*[frontend/src/app/proposal/general/general.component.scss, line 3 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3KQRJ3idZUiwk579M:-Ma3KQRJ3idZUiwk579N:b-d08tz5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.scss#L3)):*
> ```SCSS
> .general-row {
>   display: grid;
>   grid-template-columns: repeat(6, 16.6%);
> ```

16.6 % is not precise enough.
___
*[frontend/src/app/proposal/general/general.component.scss, line 6 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3KZgWCkJds2cIwKyL:-Ma3KZgWCkJds2cIwKyM:b-2vrj5v) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.scss#L6)):*
> ```SCSS
>   align-items: center;
> }
> .mat-form-field{
> ```

At least part of this rule seems general to me. Also, the name might need discussion.
___
*[frontend/src/app/proposal/general/general.component.ts, line 6 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3PunI5siLiuHvJPJv:-Ma3PunI5siLiuHvJPJw:b-d38fot) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L6)):*
> ```XML
> 
> @Component({
>   selector: 'wm-general',
> ```

The selector is too general
___
*[frontend/src/app/proposal/general/general.component.ts, line 11 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3Q2xY-wj3dF-n92vQ:-Ma3Q2xY-wj3dF-n92vR:bdzu5qw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L11)):*
> ```XML
> })
> export class GeneralComponent implements OnInit {
>   form: FormGroup;
> ```

I don't think you need this form group.
___
*[frontend/src/app/proposal/general/general.component.ts, line 13 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3PyxG6aC-HAnAUFep:-Ma3PyxG6aC-HAnAUFeq:bgk3dgn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L13)):*
> ```XML
>   form: FormGroup;
>   @Input() general!: General
>   semesterControl = new FormControl("2020-1");
> ```

There should be no initial value.
___
*[frontend/src/assets/types.ts, line 0 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3QWqP3_o65SysVZH0:-Ma3QWqP3_o65SysVZH1:b-62q244) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/assets/types.ts#L0)):*
This file should be deleted.

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/tsconfig.json, line 26 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3HesQDRU7hVvfBd39:-Ma3ruw-BxD3xqo13zYs:bgnnmte) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/tsconfig.json#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why does this have to be false?
</blockquote></details>

I  some how can not reproduce the error I having to quote the error out.
For Angular to build the appication to the smallest bundle using Ivy some package was either missing or outdated. and this would happen everytime I add an import to the app.module.js or after insa
talling new package and it will always force me to reinstall all the packages then it will work.
folling the error it leads me to stackoverflow where the easy way out was to disable Ivy which is set to be true fron Angular 9 or 8.
___
*[frontend/src/styles.scss, line 21 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JOlNEPBe0xtK3x3f:-Ma3t7Vg0SUhoe3mM-TF:bny43rm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/d9341aaa8f2260f4e96fece21d654039e8dbf533/frontend/src/styles.scss#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Styling needs discussion, regarding:

- background colour
- font size
</blockquote></details>

yes we can.
___
*[frontend/src/app/types.ts, line 16 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3Jccg9ZcJ2I4UImD7:-Ma42o0l09lmx8X4OVLK:b-hff6wv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name is too generic.
</blockquote></details>

renamed
___
*[frontend/src/app/types.ts, line 21 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JpauAvllp3TcXGUs:-Ma42mkb3rSfjj_R6L2i:b-7tfmjp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The submission number is missing.
</blockquote></details>

added
___
*[frontend/src/app/types.ts, line 24 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3JxyiA2tpeWXzccQa:-Ma41ZleEa6vAc4sAPq0:b2nign6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/types.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This needs discussion.
</blockquote></details>

yes
___
*[frontend/src/app/proposal/general/general.component.scss, line 6 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3KZgWCkJds2cIwKyL:-Ma42-2m8WCsCqKNHEye:b4qcuf1) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.scss#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

At least part of this rule seems general to me. Also, the name might need discussion.
</blockquote></details>

lets discuss
___
*[frontend/src/app/proposal/general/general.component.ts, line 6 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3PunI5siLiuHvJPJv:-Ma422vc1XQvhHmc1oUm:b-qssebl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The selector is too general
</blockquote></details>

fixed.
___
*[frontend/src/app/proposal/general/general.component.ts, line 11 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3Q2xY-wj3dF-n92vQ:-Ma42QVz08zkT_0kmcqS:ba73891) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need this form group.
</blockquote></details>

I might have missed something can we dissuss it
___
*[frontend/src/app/proposal/general/general.component.ts, line 13 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3PyxG6aC-HAnAUFep:-Ma42g0v0ppk77979p4H:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no initial value.
</blockquote></details>

removed
___
*[frontend/src/assets/types.ts, line  at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3QWqP3_o65SysVZH0:-Ma42cIH4hg80bpmW5NG:b-7rl0jd) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/assets/types.ts#L)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This file should be deleted.
</blockquote></details>

done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero, @hettlage, and @saltastroops)

___
*[frontend/tsconfig.json, line 26 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3HesQDRU7hVvfBd39:-Ma4w_W51pr3vhoOESD0:bjs8sv5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/tsconfig.json#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I  some how can not reproduce the error I having to quote the error out.
For Angular to build the appication to the smallest bundle using Ivy some package was either missing or outdated. and this would happen everytime I add an import to the app.module.js or after insa
talling new package and it will always force me to reinstall all the packages then it will work.
folling the error it leads me to stackoverflow where the easy way out was to disable Ivy which is set to be true fron Angular 9 or 8.

</blockquote></details>

It's a bit unsettling though. It would be good to know what the error is.
___
*[frontend/src/app/app.module.ts, line 27 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma4ww0E9hDlzU9m_Xxc:-Ma4ww0E9hDlzU9m_Xxd:b-gz0wnn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2c7b362603cde3fb71babec1d7552e28c2989c/frontend/src/app/app.module.ts#L27)):*
> ```XML
>     ProposalComponent,
>     InvestigatorsComponent,
>     ProposalInfoComponent,
> ```

Maybe GeneralProposalInfoComponent?
___
*[frontend/src/app/types.ts, line 16 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma4x1LG2MSxDWmahGaG:-Ma4x1LG2MSxDWmahGaH:bb9qt6c) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2c7b362603cde3fb71babec1d7552e28c2989c/frontend/src/app/types.ts#L16)):*
> ```XML
> }
> 
> export interface ProposalInfo {
> ```

Maybe GeneralProposalInfo?
___
*[frontend/src/app/types.ts, line 23 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma4x_GVANg3FEX6gqtX:-Ma4x_GVANg3FEX6gqtY:b462e96) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2c7b362603cde3fb71babec1d7552e28c2989c/frontend/src/app/types.ts#L23)):*
> ```XML
>   current_submission: Date
>   first_submission: Date
>   number_of_submissions: number
> ```

This may sound pedantic, but submission_number is probably better, so that you can go back in time.
___
*[frontend/src/app/types.ts, line 41 at r6](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma4xrdK877VV1uMCAPi:-Ma4xrdK877VV1uMCAPj:bhv9dma) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5d2c7b362603cde3fb71babec1d7552e28c2989c/frontend/src/app/types.ts#L41)):*
> ```XML
> export interface Proposal {
>   investigators: Investigator[]
>   proposal_info: ProposalInfo
> ```

proposal_info --> general_info (or just general -- that should be fine within this context).
___
*[frontend/src/app/proposal/general/general.component.scss, line 3 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3KQRJ3idZUiwk579M:-Ma4yAR-CbnEIZ21zQaW:b-cdqy4y) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.scss#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

16.6 % is not precise enough.
</blockquote></details>

`repeat(6, 1fr)` might be better.
___
*[frontend/src/app/proposal/general/general.component.ts, line 13 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3PyxG6aC-HAnAUFep:-Ma4ya0D4zLSPU7GM_Xs:bck5qxa) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.ts#L13)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

removed
</blockquote></details>

Ah, sorry, I was imprecise. What I meant is to just remove the "2020-1".

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 15 unresolved discussions (waiting on @Eb-Zeero, @hettlage, and @saltastroops)

___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 16 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma83ntk29LRzG-aNoox:-Ma83ntk29LRzG-aNooy:b-ssu7fl) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67cf44011f4eaa64131c599f5ee734876665f1d/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L16)):*
> ```XML
> 
>   constructor() {
>     new FormGroup({
> ```

The `new FormGroup` is unnecessary.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 19 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma83xqnBL5TAfbRvz7v:-Ma83xqnBL5TAfbRvz7w:bng2u0h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67cf44011f4eaa64131c599f5ee734876665f1d/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L19)):*
> ```XML
>       semester: this.semesterControl,
>     });
>     if (this.general_proposal_info){
> ```

This is unnecessary.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.html, line 33 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma82Eqj9wSaDNgIGSF5:-Ma82Eqj9wSaDNgIGSF6:btdi1t8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67cf44011f4eaa64131c599f5ee734876665f1d/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.html#L33)):*
> ```HTML
>     </div>
>     <div>{{general_proposal_info.first_submission.toISOString().split('T')[0]}}</div>
>     <div>{{general_proposal_info.current_submission.toISOString().split('T')[0]}}(#{{general_proposal_info.submission_number}})</div>
> ```

There is a space missing between the date and the submission number.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/types.ts, line 25 at r7](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma8FE1JBNtH1DzzlxWo:-Ma8FE1JBNtH1DzzlxWp:bwdkfex) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a67cf44011f4eaa64131c599f5ee734876665f1d/frontend/src/app/types.ts#L25)):*
> ```XML
>   submission_number: number
>   phase: number
>   semesters: Semester[]
> ```

Add a Todo

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @saltastroops)

*[a discussion](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma9qFFe0tNUN_4deDvB:-Ma9qFFf7f8xcNNR_yHB:bl3s6r9) (no related file):*
Variable for CSS will be addapted from the block-summary pr to avoide more confilcts

---
___
*[frontend/tsconfig.json, line 26 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3HesQDRU7hVvfBd39:-Ma7lIxy7QMPHl1N6fa7:ba7kygn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/tsconfig.json#L26)):*
> It's a bit unsettling though. It would be good to know what the error is.
it is true by default I can remove it for now till I get the same error once again.
___
*[frontend/src/app/proposal/general/general.component.scss, line 6 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-Ma3KZgWCkJds2cIwKyL:-Ma9n4vG5G_nufr9aK7H:b-in1xxu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/a4591e0a7e6a6b0e121ef0b066bd9f2c3a321000/frontend/src/app/proposal/general/general.component.scss#L6)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

lets discuss
</blockquote></details>

leaving this for now

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 6 unresolved discussions (waiting on @saltastroops)

___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 12 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaD2QrkCEB4MSiWKJS4:-MaD2QrkCEB4MSiWKJS5:b-4ze24a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L12)):*
> ```XML
> export class GeneralProposalInfoComponent implements OnInit {
>   @Input() general_proposal_info!: GeneralProposalInfo
>   currentSemester: string = ""
> ```

This should be obtained from the proposal.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 13 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaD46gd-0fUasV30tU2:-MaD46gd-0fUasV30tU3:b-jt4vvj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L13)):*
> ```XML
>   @Input() general_proposal_info!: GeneralProposalInfo
>   currentSemester: string = ""
>   semesterControl  = new FormControl(this.currentSemester);
> ```

There should be no default value:

`semesterControl  = new FormControl();`
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 17 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaCvd1gDxPhonZtFxjk:-MaCvd1gDxPhonZtFxjl:b-iif5fx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L17)):*
> ```XML
> 
>   ngOnInit(): void {
>     // this is where you will the start semester
> ```

This isn't ideal. The initially selected semester should be the one of the latest submission (i.e. the current semester)
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 19 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaD4GT1D1xgwAuLrlUm:-MaD4GT26eq8YgT5A2ar:b-sr77uk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L19)):*
> ```XML
>     // this is where you will the start semester
>     const _sem = this.general_proposal_info.semesters[0]
>     this.semesterControl = new FormControl(`${_sem.year}-${_sem.semester}`)
> ```

Better: Use the Semester object as the value (with here and in the template).

`this.semesterControl.setValue(_sem);`
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.html, line 25 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaD4ck88nQL-aWz3Xfs:-MaD4ck88nQL-aWz3Xft:b8uqsba) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.html#L25)):*
> ```HTML
>     <div>
>         <mat-select class="mat-focus-indicator mat-raised-button mat-button-base mat-primary" [formControl]="semesterControl">
>           <mat-option *ngFor="let s of general_proposal_info.semesters" [value]="s.year.toString() + '-' + s.semester.toString()">
> ```

[value]="s"

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 17 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaCvd1gDxPhonZtFxjk:-MaDXuBQ4mhHqZas9C3q:bek14w8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This isn't ideal. The initially selected semester should be the one of the latest submission (i.e. the current semester)
</blockquote></details>

Ha ha ha ha ha

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: all files reviewed, 6 unresolved discussions (waiting on @hettlage and @saltastroops)

___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 13 at r8](https://reviewable.io/reviews/saltastroops/web-manager-2021/19#-MaD46gd-0fUasV30tU2:-MaE-0IRAtcPU-KFhrgA:btb3egs) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/7460bab8605f4c916a4ed09e58131a38f2505c32/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no default value:

`semesterControl  = new FormControl();`
</blockquote></details>

and then I have no semester to dispaly

**Review by hettlage — APPROVED** [review]
> Reviewed 5 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/19)* status: 22 of 34 files reviewed, 2 unresolved discussions (waiting on @hettlage and @saltastroops)

**Pull request merged**
