### PR TITLE
MOS Extras

### PR DESCRIPTION
**Pull request by Eb-Zeero**
other barcode fixed.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/styles.scss, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N-Tqp1p6IO_zBy0AAUN:-N-Tqp1q5WFdYsy-dAi9:b6m9cf9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5c357dbeea90aca1a0191b42f7e09ecf18aaac36/src/styles.scss#L53)):*
> ```SCSS
> $orange-background: #ccaa00;
> $yellow-background: #e7fa5a;
> $dark-red-background: #ff9a9a;
> ```

This is very similar to the other red background colour used in the MOS table.

**Review by saltastroops — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/styles.scss, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N-Tqp1p6IO_zBy0AAUN:-N0-vx4v7tB6HAZ-HMjw:bmg78ik) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5c357dbeea90aca1a0191b42f7e09ecf18aaac36/src/styles.scss#L53)):*
> This is very similar to the other red background colour used in the MOS table.
It is for mos I just need thsi to have some shade of the same red.
do you sudjest I use a different color(if so which one?) or use the same one.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/styles.scss, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N-Tqp1p6IO_zBy0AAUN:-N01CQGq312BIWqGWOD1:b-cha7nk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5c357dbeea90aca1a0191b42f7e09ecf18aaac36/src/styles.scss#L53)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

> This is very similar to the other red background colour used in the MOS table.
It is for mos I just need thsi to have some shade of the same red.
do you sudjest I use a different color(if so which one?) or use the same one.
 
</blockquote></details>

This is very similar to the other red background colour used in the MOS table.
 It is for mos I just need thsi to have some shade of the same red.
 do you sudjest I use a different color(if so which one?) or use the same one.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @saltastroops)

___
*[src/styles.scss, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N-Tqp1p6IO_zBy0AAUN:-N01xcRGBCIh6wr-CvEi:b443040) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5c357dbeea90aca1a0191b42f7e09ecf18aaac36/src/styles.scss#L53)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

This is very similar to the other red background colour used in the MOS table.
 It is for mos I just need thsi to have some shade of the same red.
 do you sudjest I use a different color(if so which one?) or use the same one.

</blockquote></details>

In personally think that the same colour would make more sense than two different shades which are somewhat hard to tell apart, as long as you can easily see from the table row content why the colour is red.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @hettlage and @saltastroops)

___
*[src/styles.scss, line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N-Tqp1p6IO_zBy0AAUN:-N05Lei_1kgGm_HDUGtH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5c357dbeea90aca1a0191b42f7e09ecf18aaac36/src/styles.scss#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

In personally think that the same colour would make more sense than two different shades which are somewhat hard to tell apart, as long as you can easily see from the table row content why the colour is red.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 58 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N05jQhLDx8IEu27I4Un:-N05jQhLDx8IEu27I4Uo:b5dtcmc) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/87dc27883ecb8f517cf06ad666858bb70d3cc876/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L58)):*
> ```XML
>       return "is-ready-mask-background";
>     }
>     if (
> ```

I'd suggest you combine the two if's for is-take-mask-out-background into a single one.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/app/mos/mos-blocks-table/mos-blocks-table.component.ts, line 58 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/112#-N05jQhLDx8IEu27I4Un:-N061blN2HKdPKZxMWBX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/87dc27883ecb8f517cf06ad666858bb70d3cc876/src/app/mos/mos-blocks-table/mos-blocks-table.component.ts#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you combine the two if's for is-take-mask-out-background into a single one.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
