### PR TITLE
Mos Slit mask

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.html, line 14 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7_u6N1T9y6VdbFdua:-Mf7_u6N1T9y6VdbFdub:bcn6qjm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.html#L14)):*
> ```HTML
>       Slit mask
>     </div>
>     <div>
> ```

Spacing and alignment need checking.

There may be no "cut by" or comment.
___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7aetp7mWPpdLU8CZT:-Mf7aetp7mWPpdLU8CZU:b-241wz2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts#L12)):*
> ```XML
>     type: string;
>     barcode: string
>     mask: {
> ```

I don't think there is a need for grouping in a mos property.

The type property is unnecessary.

The edgeLength property is unnecessary (that's a user input).

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.html, line 14 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7_u6N1T9y6VdbFdua:-MfCdLe095FLXdOJbRZt:b9y7xog) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.html#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Spacing and alignment need checking.

There may be no "cut by" or comment.
</blockquote></details>

thi stable is hard to allign. 
please can I dedicate another PR for just this
___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7aetp7mWPpdLU8CZT:-MfCdj5mEqiC8iYdyNnS:b-fvpg5a) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts#L12)):*
> I don't think there is a need for grouping in a mos property.
?

The type:  I do not know why it is unnecessary
The edgeLength: use input this and I believe it should go to the database somewhat.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7aetp7mWPpdLU8CZT:-MfCjfW49oqBJGFrXPGy:b3f3i3p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts#L12)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> I don't think there is a need for grouping in a mos property.
?

The type:  I do not know why it is unnecessary
The edgeLength: use input this and I believe it should go to the database somewhat.
</blockquote></details>

The type would always be MOS., I think.

The edgeLength is used for generating a Code file on the fly; I'm pretty sure it is not stored in the database.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/59)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts, line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/59#-Mf7aetp7mWPpdLU8CZT:-MfFCMJwBWVhNVo4IEMX:b-9qse9q) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c838fef23a9a1548a299cc5e56400feca091e3c8/frontend/src/app/proposal/instruments/rss/mos-slit-mask-table/mos-slit-mask-table.component.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The type would always be MOS., I think.

The edgeLength is used for generating a Code file on the fly; I'm pretty sure it is not stored in the database.
</blockquote></details>

I'm still not convinced you need the mos property -- you could flatten it.  But I guess this question will turn up when we discuss types, so I'll accept the PR for the time being.

**Pull request merged**
