### PR TITLE
Executed observation

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[package.json, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7tYmDDsEr6NJjLxH3:-Mb7tYmE-lQBn4NC71VV:b-b73ghk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/package.json#L1)):*
> ```JSON
> {
> ```

This file should be removed (as should be the yarn.lock file).
___
*[frontend/package.json, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7tpG68ZpwtsItJHt5:-Mb7tpG68ZpwtsItJHt6:bbkxarr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/package.json#L22)):*
> ```JSON
>     "@angular/platform-browser-dynamic": "~11.2.13",
>     "@angular/router": "~11.2.13",
>     "angular-svg-icon": "^11.2.0",
> ```

This is outdated (was are some of the icons).
___
*[frontend/src/app/types.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7qnco4zTDfO2vA_mE:-Mb7qnco4zTDfO2vA_mF:b-n04hgt) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L75)):*
> ```XML
> }
> 
> export interface ExecutedObservations {
> ```

ExecutedObservations ---> ExecutedObservation
___
*[frontend/src/app/types.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7cpIhCbM98VX4ntUx:-Mb7cpIiEM7vJAWX6qv3:b-40ar1w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L77)):*
> ```XML
> export interface ExecutedObservations {
>   id: number;
>   name: string;
> ```

Is that the block name? In this case block_name might be clearer. Also, you need the block id. So may use block (with type BlockIdentifier) instead?
___
*[frontend/src/app/types.ts, line 85 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7qUpz0OQAOHxOhlmv:-Mb7qUpz0OQAOHxOhlmw:b-7nrqne) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L85)):*
> ```XML
>   accepted: boolean;
>   rejection_reason: string | null;
>   request_data: boolean;
> ```

request_data arguably should not be part of this model.
___
*[frontend/src/app/proposal/block-summaries/block-summaries.component.html, line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7sjLl6ieC28mxkQ3v:-Mb7sjLm3cbvBAiRPutY:b-u10s2x) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/block-summaries/block-summaries.component.html#L26)):*
> ```HTML
>       <div>{{ b.done_visits }}/{{ b.requested_block_visits }}</div>
>       <div *ngIf="b.observable_tonight" class="is-green">
>         <svg-icon class="icon" src="/assets/icons/noun_check.svg"></svg-icon>
> ```

Now there are two files for checkmarks and for crosses...
___
*[frontend/src/app/proposal/investigators/investigators.component.html, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7ub7-0VON6RMkhWIX:-Mb7ub7-0VON6RMkhWIY:b-j6uflw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/investigators/investigators.component.html#L16)):*
> ```HTML
>     <div class="investigator-row row">
>       <div *ngIf="i.is_pc">
>         <svg-icon class="icon" src="/assets/icons/noun_check.svg"></svg-icon>
> ```

As there is no alt tag any longer, there is an accessibility issue.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html, line 58 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7uq3H1MaMU9jw7zgJ:-Mb7uq3H1MaMU9jw7zgK:b-15ousk) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html#L58)):*
> ```HTML
>       <div>
>         <label class="checkbox">
>           <input type="checkbox" [(ngModel)]="e.request_data" (change)="requestData(e.id)">
> ```

The checkboxes aren't properly aligned horizontally.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7vI8J5h620BaZVTEr:-Mb7vI8J5h620BaZVTEs:bofw0js) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L20)):*
> ```XML
>   selectDeselectAll(): void {
>     if (this.selectAll){
>       this.executed_observations.map(
> ```

map ---> forEach

You can simplify this:

```
      this.executed_observations.map(
        e => {
          e.request_data = this.selectAll;
        }
     )
```

___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7wPjE1eiiMXYdDNsK:-Mb7wPjE1eiiMXYdDNsL:b-eorjfz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L36)):*
> ```XML
>   }
> 
>   requestData(blockId: number): void {
> ```

This is more like toggleRequestData... Also, you could get rid of the two-way binding in the template. (Maybe we can chat briefly about this?)
___
*[python/static/js/salt-block-view.js, line 39 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7wwAl0lB49ZwX_PcT:-Mb7wwAl0lB49ZwX_PcU:b-7j6bsp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/python/static/js/salt-block-view.js#L39)):*
> ```JavaScript
>    */
>   connectedCallback() {
>     this.proposal_code = this.getAttribute("proposal-code");
> ```

No n eed for changing, really. This file will disappear soon.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/app.module.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbLzgIXAt1F0T5L1Pv_:-MbLzgIXAt1F0T5L1Pva:btgn2ds) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/app.module.ts#L19)):*
> ```XML
> import { BlockSelectionComponent } from './proposal/block-view/block-selection/block-selection.component';
> import { SummaryOfExecutedObservationsComponent } from './proposal/summary-of-executed-observations/summary-of-executed-observations.component';
> import { CounterComponent } from './proposal/counter/counter.component';
> ```

CounterComponent and FeedbackComponent should be deleted.
___
*[frontend/src/app/proposal/proposal.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM-AxJDM5AYNZfSQe4:-MbM-AxJDM5AYNZfSQe5:bw3hosr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/proposal.component.html#L9)):*
> ```HTML
>     <wm-general-proposal-info
>       [general_proposal_info]="p.general_info"
>       [current_semester]="p.general_info.current_semester"
> ```

There should be no need to pass the semester separately.
___
*[frontend/src/app/proposal/counter/counter.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM00Gy65BOBq7q3o2K:-MbM00Gy65BOBq7q3o2L:b-u2bqpp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.html#L1)):*
> ```HTML
> <button (click)="decrement()">-</button>
> ```

Should be removed.
___
*[frontend/src/app/proposal/counter/counter.component.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM05699v6b_oD4_lxf:-MbM05699v6b_oD4_lxg:b-u2bqpp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.ts#L1)):*
> ```XML
> import {Component, Input, OnInit} from '@angular/core';
> ```

Should be removed.
___
*[frontend/src/app/proposal/counter/counter.component.spec.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM07AMEV-zEwghGtx0:-MbM07AMEV-zEwghGtx1:b-u2bqpp) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.spec.ts#L1)):*
> ```XML
> import { render, screen, fireEvent } from '@testing-library/angular';
> ```

Should be removed.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0INuEvnSIdMIGDmy:-MbM0INuEvnSIdMIGDmz:b-czmeaq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L17)):*
> ```XML
> 
>   ngOnInit(): void {
>     console.log('>>>>: ', this.general_proposal_info);
> ```

Unnecessary console.log
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0RPwA3AguBkRsA5v:-MbM0RPwA3AguBkRsA5w:blbzzgi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts#L11)):*
> ```XML
> 
> 
>   it('should create #################', async () => {
> ```

Why all these hash signs?
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0liM5S4Sf7Pbgdhl:-MbM0liM5S4Sf7Pbgdhm:baak7bh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts#L11)):*
> ```XML
> 
> 
>   it('should create #################', async () => {
> ```

Is this test necessary?
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html, line 59 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM75hH7lyp6YQq2EUE:-MbM75hH7lyp6YQq2EUF:bnm00tq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html#L59)):*
> ```HTML
>       <div>{{e.rejection_reason}}</div>
>       <ng-template [ngIf]="e.accepted">
>         <div><button class="button is-danger is-small">Reject</button></div>
> ```

I'd suggest that the accept and reject buttons have the same size.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM597K8x1FxVkofR1N:-MbM597K8x1FxVkofR1O:bbiuobi) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L9)):*
> ```XML
>   styleUrls: ['./summary-of-executed-observations.component.scss']
> })
> export class SummaryOfExecutedObservationsComponent implements OnInit {
> ```

I'm afraid the selection is somewhat broken. :-(

Can we talk about this?
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM5z06-ZICDqzfDCUs:-MbM5z06-ZICDqzfDCUt:bydijy3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L20)):*
> ```XML
> 
>   selectDeselectAll(): void {
>     this.blocksToDownload = [];
> ```

You are not requesting to download blocks, but observations (block visits). So the relevant id is not the block id, but the observation id.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.spec.ts, line 36 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM6Jqj5eZ_hTbHoXmw:-MbM6Jqj5eZ_hTbHoXmx:b6oqgrj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.spec.ts#L36)):*
> ```XML
>     });
>   });
> });
> ```

There are various tests missing... :-)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[package.json, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7tYmDDsEr6NJjLxH3:-MbHTrxtEu_jassKF2Ek:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/package.json#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This file should be removed (as should be the yarn.lock file).
</blockquote></details>

Done.
___
*[frontend/package.json, line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7tpG68ZpwtsItJHt5:-MbGmJaN1oQhcksHbAT5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/package.json#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is outdated (was are some of the icons).
</blockquote></details>

Done.
___
*[frontend/src/app/app.module.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbLzgIXAt1F0T5L1Pv_:-Mb_QMoBEFOHP8YkT8P3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/app.module.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

CounterComponent and FeedbackComponent should be deleted.
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7qnco4zTDfO2vA_mE:-MbGmRiT0JbDU2y5pxe7:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ExecutedObservations ---> ExecutedObservation
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7cpIhCbM98VX4ntUx:-MbGopeH6WRHfqXTBVeP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is that the block name? In this case block_name might be clearer. Also, you need the block id. So may use block (with type BlockIdentifier) instead?
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 85 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7qUpz0OQAOHxOhlmv:-MbLSL_d2p8SVATSUoKT:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/types.ts#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

request_data arguably should not be part of this model.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/block-summaries/block-summaries.component.html, line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7sjLl6ieC28mxkQ3v:-MbGnjGF5YeqJbUnZWu-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/block-summaries/block-summaries.component.html#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now there are two files for checkmarks and for crosses...
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/counter/counter.component.html, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM00Gy65BOBq7q3o2K:-Mb_R7dd1uhNksO3pclh:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be removed.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/counter/counter.component.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM05699v6b_oD4_lxf:-Mb_R8EX8nhjHMPBp8Jn:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be removed.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/counter/counter.component.spec.ts, line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM07AMEV-zEwghGtx0:-Mb_R8kW96pFU5_HRTAN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/counter/counter.component.spec.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be removed.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts, line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0INuEvnSIdMIGDmy:-Mb_ROcs5Z_frPFWx3Pd:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unnecessary console.log
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0RPwA3AguBkRsA5v:-Mb_RTNo-YMy9JF_Q4Si:b-gc0wm8) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why all these hash signs?
</blockquote></details>

to easly spot my test will remove I pushed everying while I was testing
___
*[frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM0liM5S4Sf7Pbgdhl:-Mb_RgBV9KokQNci8PKE:bdqn4ym) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/general-proposal-info/general-proposal-info.component.spec.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this test necessary?
</blockquote></details>

yes working on the tests
___
*[frontend/src/app/proposal/investigators/investigators.component.html, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7ub7-0VON6RMkhWIX:-MbGrHS11ianiXGKEQyp:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/investigators/investigators.component.html#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As there is no alt tag any longer, there is an accessibility issue.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html, line 58 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7uq3H1MaMU9jw7zgJ:-MbLSWMt21HxKPcWmg_l:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The checkboxes aren't properly aligned horizontally.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7wPjE1eiiMXYdDNsK:-MbGru-x3fgKxJrDqcti:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is more like toggleRequestData... Also, you could get rid of the two-way binding in the template. (Maybe we can chat briefly about this?)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/proposal/investigators/investigators.component.html, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7ub7-0VON6RMkhWIX:-Mb_nkNHAAnerhxeyCAs:b-atndwb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/investigators/investigators.component.html#L16)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually this is the wrong icon.. :-)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: 20 of 31 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/proposal/proposal.component.html, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM-AxJDM5AYNZfSQe4:-MbjzTot4YoT20FYIkgt:b90z0uh) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/proposal.component.html#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be no need to pass the semester separately.
</blockquote></details>

will be done on the future
___
*[frontend/src/app/proposal/investigators/investigators.component.html, line 16 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7ub7-0VON6RMkhWIX:-MbjzRYD3RXt-ntZTjIh:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/frontend/src/app/proposal/investigators/investigators.component.html#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually this is the wrong icon.. :-)
</blockquote></details>

fixed
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 9 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM597K8x1FxVkofR1N:-MbjzP6e1vTnLworrz1x:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm afraid the selection is somewhat broken. :-(

Can we talk about this?
</blockquote></details>

fixed
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts, line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM5z06-ZICDqzfDCUs:-MbjzbQ29NH325PenK9p:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are not requesting to download blocks, but observations (block visits). So the relevant id is not the block id, but the observation id.
</blockquote></details>

removed
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.spec.ts, line 36 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbM6Jqj5eZ_hTbHoXmw:-MbkMt8e0pDxE4uD24cb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/aa1663e6ed3460540426b79f645ed8b2548db120/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.spec.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There are various tests missing... :-)
</blockquote></details>

Done.
___
*[python/static/js/salt-block-view.js, line 39 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-Mb7wwAl0lB49ZwX_PcT:-MbjzfdJ9DRcKHWuV3WQ:bq8w6oj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/62b4c27a5dde9e20d6a3ad32014cb0f376c54f2c/python/static/js/salt-block-view.js#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No n eed for changing, really. This file will disappear soon.
</blockquote></details>

not relevent

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 11 files at r4, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html, line 35 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbmES798P_mEy9vMpNS:-MbmES798P_mEy9vMpNT:bqqkil2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5bbd59cba24096108d3252e5b6d1140e4c256e2a/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html#L35)):*
> ```HTML
>       <div>
>         {{ e.block_identifier.name }}
>         <span>(view details)</span>
> ```

I've removed the link. I'll explain why in a chat.
___
*[frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html, line 43 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/29#-MbmEdSR7rqk7lr2Y5cu:-MbmEdSR7rqk7lr2Y5cv:buzroep) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/5bbd59cba24096108d3252e5b6d1140e4c256e2a/frontend/src/app/proposal/summary-of-executed-observations/summary-of-executed-observations.component.html#L43)):*
> ```HTML
>         <div *ngFor="let t of e.targets">
>           <div>
>             <span>{{ t }}</span>
> ```

I've removed the links. I'll explain why in a chat.

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
