### PR TITLE
Api endpoints

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/46)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/46)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html, line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/46#-MdSaO6NEOPh6DcEapOR:-MdSaO6R47dLxD_MZYzW:bbj4ohm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cd16d77c7f271d7f74f486213863df3dc9c63d4b/frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html#L25)):*
> ```HTML
>         <span class="has-text-link" tooltip="{{ a.tac_comment }}">
>           Show comment</span
>         >
> ```

If I may ask, is there a reason why you put the ">" sign here instead of next to span?

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/46)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html, line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/46#-MdSaO6NEOPh6DcEapOR:-MdSyH-4AjMrWdLmsfhZ:bo0q366) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cd16d77c7f271d7f74f486213863df3dc9c63d4b/frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html#L25)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

If I may ask, is there a reason why you put the ">" sign here instead of next to span?
</blockquote></details>

Nope. I suspect it wasn't me, but PrettierJS... :)

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/46)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @hettlage and @mofokeng-chaka)

___
*[frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html, line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/46#-MdSaO6NEOPh6DcEapOR:-MdSyhcX955UgQqw6cPA:bwic0rv) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/cd16d77c7f271d7f74f486213863df3dc9c63d4b/frontend/src/app/proposal/time-allocation-table/time-allocation-table.component.html#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope. I suspect it wasn't me, but PrettierJS... :)
</blockquote></details>

Okay, thanks!

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
