### PR TITLE
Navigation Bar

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/styles.scss, line 264 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRWJITAgWP83ljLjE1:-MyRWJITAgWP83ljLjE2:b-2csmoo) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/styles.scss#L264)):*
> ```SCSS
> }
> 
> $navbar-item-color: lighten($text, 30%);
> ```

Shouldn't these changes be in the styles file for the navigation bar?
___
*[src/app/app.module.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRXewUEQVTiijCXVpw:-MyRXewUEQVTiijCXVpx:bk06wjn) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/app.module.ts#L77)):*
> ```XML
> import { RealProposalService } from "./service/real/real-proposal.service";
> import { LoadingSpinnerComponent } from "./shared/loading-spinner/loading-spinner.component";
> import { AdminNavigationComponent } from './navigation-bar/admin-navigation/admin-navigation.component';
> ```

I'm not entirely convinced that splitting the navigation bar into different components is necessary.
___
*[src/app/app.module.ts, line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRXneK5K7REyg7tM-y:-MyRXneK5K7REyg7tM-z:b-l9ha0w) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/app.module.ts#L145)):*
> ```XML
>     AdminNavigationComponent,
>     OptionsNavigationComponent,
>     SaNavigatorComponent,
> ```

SaNavigator > SaNavigation
___
*[src/app/navigation-bar/navigation-bar.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRYKQV6c-0l82qqlw8:-MyRYKQV6c-0l82qqlw9:borcxs9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L1)):*
> ```HTML
> <div>
> ```

I don't think you should use blue colour.

The cursor shape should change the hovering over top level menu items.

I don't think there should be a Proposals menu item at this point in time.

You might consider a slightly thinner border underneath the active tab.

The Go to text field should have a placeholder text ("Proposal code").

The Go to text field and button are slightly misaligned vertically.

I don't think you should use click listeners -- they seem to break things. (And I don't think you need it; see https://angular.io/api/router/RouterLinkActive). This implies that I don't think session storage is necessary.

I don't think the active tab should be underlined in the secondary menus.

The overall navigation bar content might need discussion at some point -- but I guess it will evolve anyway. :-)
___
*[src/app/navigation-bar/navigation-bar.component.html, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySBhZW4oHOYVO-P2v5:-MySBhZW4oHOYVO-P2v6:bwd4wv3) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L17)):*
> ```HTML
>           </div>
>           <wm-options-navigation
>             *ngIf="hasAnyRole(user, ['Investigator', 'SALT Operator', 'SALT Astronomer'])"
> ```

I think this menu should be available to everyone?
___
*[src/app/navigation-bar/navigation-bar.component.html, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySByN58xJ6k2comLpS:-MySByN58xJ6k2comLpT:b-iqzs4h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L27)):*
> ```HTML
>             [user]="null" ></wm-admin-navigation>
>           <wm-sa-navigator
>             *ngIf="hasAnyRole(user, ['SALT Astronomer'])"
> ```

This is too restrictive. The menu might make sense flor SOs as well, and the MOS page must be available to Technicians.
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySAYS_79vtoVs_ljx9:-MySAYS_79vtoVs_ljxA:b-cqma45) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L7)):*
> ```HTML
>   <div class="navbar-dropdown">
>     <a [routerLink]="['/investigators']" class="navbar-item" [ngClass]="selectedUri === 'investigators' ? 'is-tab is-active' : ''" (click)="selectUri('/investigators')">
>       List Investigators
> ```

Should be accessible to Admins and SAs only, I think
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySAldkEUc2LjECXO4g:-MySAldkEUc2LjECXO4h:bfz26sb) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L19)):*
> ```HTML
>     </a>
>     <a [routerLink]="['user-options']" class="navbar-item " [ngClass]="selectedUri === 'user-options' ? 'is-tab is-active' : ''" (click)="selectUri('user-options')">
>       Options
> ```

I'm not sure we need an options page?
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySB2XrEibGijcwD4df:-MySB2XrEibGijcwD4dg:b-x57j0u) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L21)):*
> ```HTML
>       Options
>     </a>
>     <a [routerLink]="['edit-rights']" class="navbar-item " [ngClass]="selectedUri === 'edit-rights' ? 'is-tab is-active' : ''" (click)="selectUri('edit-rights')">
> ```

Should only be accessible to Ad mins
___
*[src/app/types/user.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySCOB-1ODZu_wcXAQm:-MySCOB-1ODZu_wcXAQn:b-6yup0i) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/types/user.ts#L3)):*
> ```XML
> export type UserRole =
>   | "Administrator"
>   | "Investigator"
> ```

I don;t. think the role is needed.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[src/styles.scss, line 264 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRWJITAgWP83ljLjE1:-MymCI552ZEta1BsevLj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/styles.scss#L264)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't these changes be in the styles file for the navigation bar?
</blockquote></details>

Done.
___
*[src/app/app.module.ts, line 77 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRXewUEQVTiijCXVpw:-MysrbFr20b-RXEpxhTO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/app.module.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not entirely convinced that splitting the navigation bar into different components is necessary.
</blockquote></details>

Done.
___
*[src/app/app.module.ts, line 145 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRXneK5K7REyg7tM-y:-MymDy74EP-DwPg2vsOQ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/app.module.ts#L145)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

SaNavigator > SaNavigation
</blockquote></details>

Done.
___
*[src/app/navigation-bar/navigation-bar.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MyRYKQV6c-0l82qqlw8:-MypuFyL38kwwV8El_fb:bpwmgu2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L1)):*
> I don't think you should use blue colour.
changed
> The cursor shape should change the hovering over top level menu items.
fixed
> I don't think there should be a Proposals menu item at this point in time.
removed
> You might consider a slightly thinner border underneath the active tab.
done
> The Go to text field should have a placeholder text ("Proposal code").
Done
> The Go to text field and button are slightly misaligned vertically.
Fixed
> I don't think you should use click listeners -- they seem to break things. (And I don't think you need it; see https://angular.io/api/router/RouterLinkActive). This implies that I don't think session storage is necessary.
I have new problems I am failing to understand exatly what is happening
> I don't think the active tab should be underlined in the secondary menus.
removed
> The overall navigation bar content might need discussion at some point -- but I guess it will evolve anyway. :-)
yes we will
___
*[src/app/navigation-bar/navigation-bar.component.html, line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySBhZW4oHOYVO-P2v5:-Mysp1mzE0oaRWNIFoV1:bb6un1j) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this menu should be available to everyone?
</blockquote></details>

Done
___
*[src/app/navigation-bar/navigation-bar.component.html, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySByN58xJ6k2comLpS:-MyspeTN2p9rzT3mU05T:b1s82b4) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is too restrictive. The menu might make sense flor SOs as well, and the MOS page must be available to Technicians.
</blockquote></details>

We do not have the role yet
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 7 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySAYS_79vtoVs_ljx9:-MyspwJl23SaN16DTmzv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be accessible to Admins and SAs only, I think
</blockquote></details>

Done.
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySAldkEUc2LjECXO4g:-Mysq4DB7l3dK6oYV0if:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure we need an options page?
</blockquote></details>

Done.
___
*[src/app/navigation-bar/options-navigation/options-navigation.component.html, line 21 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySB2XrEibGijcwD4df:-Mysq8Cd6Ec3shTzKbGb:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/options-navigation/options-navigation.component.html#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should only be accessible to Ad mins
</blockquote></details>

Done.
___
*[src/app/types/user.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySCOB-1ODZu_wcXAQm:-Mysq9Fr2pZF2kS4PxKL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/types/user.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don;t. think the role is needed.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/styles.scss, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-QP2_5AD1ivTT_6OD:-Mz-QP2a2AEfHIsx7JBo:b-wqxsro) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/styles.scss#L11)):*
> ```SCSS
> $size-6: 0.8rem;
> 
> $navbar-burger-color: #f1f1f1;
> ```

Are you using these anywhere? And, given they are navbar-specific, are they necessary and should they be defined in the general styles.scss?
___
*[src/app/navigation-bar/navigation-bar.component.html, line 65 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-U2xeB5o0DgFSZYwX:-Mz-U2xeB5o0DgFSZYwY:b-40219e) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/app/navigation-bar/navigation-bar.component.html#L65)):*
> ```HTML
>                 Required Filters
>               </a>
>               <a class="navbar-item" routerLink="filters-no-longer-need">
> ```

"filters-no-longer-need" > "filters-no-longer-needed"

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: 24 of 25 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[src/styles.scss, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-QP2_5AD1ivTT_6OD:-MzTjdzW4l0fTwJJ6zOB:bjkx6go) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/styles.scss#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are you using these anywhere? And, given they are navbar-specific, are they necessary and should they be defined in the general styles.scss?
</blockquote></details>

thise are bulma defaults variables for the narvbar.
they need to be set before bulma is imported. 
___
*[src/app/navigation-bar/navigation-bar.component.html, line 65 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-U2xeB5o0DgFSZYwX:-MzTkZ2t3o0Rm_d4fOJF:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/app/navigation-bar/navigation-bar.component.html#L65)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"filters-no-longer-need" > "filters-no-longer-needed"
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/app/navigation-bar/navigation-bar.component.html, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySByN58xJ6k2comLpS:-Mz-VgP6EDIwD-YrUf06:b-6opn2k) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L27)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

We do not have the role yet
</blockquote></details>

Maybe we should add them? :-) But I think we have the SO already?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: 23 of 27 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/app/navigation-bar/navigation-bar.component.html, line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MySByN58xJ6k2comLpS:-MzZS09F7cBadfw0afDj:b-896fjx) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/c0cfec006a04ca5875b9f46a929f3dc7e4dae405/src/app/navigation-bar/navigation-bar.component.html#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe we should add them? :-) But I think we have the SO already?
</blockquote></details>

Done

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: all files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero)

___
*[cypress/integration/navigation-bar.spec.ts, line 104 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZV40gCr9GY44FsbEQ:-MzZV40gCr9GY44FsbER:b-hs6gnj) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/integration/navigation-bar.spec.ts#L104)):*
> ```XML
> });
> 
> describe("Navigation available tabs", () => {
> ```

Maybe: Navigation available tabs > Navigation bar
___
*[cypress/integration/navigation-bar.spec.ts, line 12 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZWWaHBmaywD0-40jG:-MzZWWaHBmaywD0-40jH:bgphnq9) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/71f36809a9bd15c1cf14a2789d2f5788240d01a7/cypress/integration/navigation-bar.spec.ts#L12)):*
> ```XML
> const USERNAME = "hettlage";
> const ADMINISTRATOR = "nhlavutelo";
> const SALT_ASTRONOMER = "MoSalt";
> ```

I'm a bit apprehensive of including Moses' username in the source code. I'd suggest to remove it and comment out SA tests for the moment.
___
*[cypress/support/components/navigation-bar.ts, line 14 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVLGZ9sNxwExWUY1W:-MzZVLGZ9sNxwExWUY1X:b-ma30s7) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L14)):*
> ```XML
> const OPTIONS_TAB = '[data-test="options-tab"]';
> const GRAVITATIONAL_WAVES_TAB = '[data-test="gravitational-waves-tab"]';
> const ADMINS_TAB = '[data-test="admins-tab"]';
> ```

ADMINS_TAB > ADMIN_TAB
admins-tab > admin-tab
___
*[cypress/support/components/navigation-bar.ts, line 103 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVTLVCetCbWDbCGXN:-MzZVTLVCetCbWDbCGXO:b-18csxy) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L103)):*
> ```XML
>     cy.get(OPTIONS_TAB).should("not.exist");
>   }
>   static hasAdminsTab() {
> ```

hasAdminsTab > hasAdminTab
___
*[cypress/support/components/navigation-bar.ts, line 106 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVUMc30f4KHNi5jTY:-MzZVUMdEa0QY45LsSgj:bp129cq) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L106)):*
> ```XML
>     cy.get(ADMINS_TAB).should("be.visible");
>   }
>   static hasNoAdminsTab() {
> ```

hasNoAdminsTab > hasNoAdminTab
___
*[src/styles.scss, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-QP2_5AD1ivTT_6OD:-MzZRweS-2QKEYHVpK6-:b-monxw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/styles.scss#L11)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

thise are bulma defaults variables for the narvbar.
they need to be set before bulma is imported. 
</blockquote></details>

It might be a good idea to add a comment to make this clear. Something like:

```
// Variables overriding Bulma values. These must be set before Bulma is imported.

... variables here, starting with $primary, I guess?

// End: Variables overriding Bulma values
```
___
*[src/app/navigation-bar/navigation-bar.component.html, line 36 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVa_N9fO0D73aHKUH:-MzZVa_N9fO0D73aHKUI:b-6nn0t6) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/src/app/navigation-bar/navigation-bar.component.html#L36)):*
> ```HTML
>           </div>
>           <div class="navbar-item has-dropdown is-hoverable" *ngIf="hasAnyRole(user, ['Administrator'])">
>             <a class="navbar-link" data-test="admins-tab">
> ```

admins-tab > admin-tab

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: 24 of 27 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[cypress/integration/navigation-bar.spec.ts, line 104 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZV40gCr9GY44FsbEQ:-MzZcrg-1NbTe66InHNM:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/integration/navigation-bar.spec.ts#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe: Navigation available tabs > Navigation bar
</blockquote></details>

Done.
___
*[cypress/integration/navigation-bar.spec.ts, line 12 at r5](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZWWaHBmaywD0-40jG:-MzZcbBk5vR_ZZ1X188h:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/71f36809a9bd15c1cf14a2789d2f5788240d01a7/cypress/integration/navigation-bar.spec.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm a bit apprehensive of including Moses' username in the source code. I'd suggest to remove it and comment out SA tests for the moment.
</blockquote></details>

Done.
___
*[cypress/support/components/navigation-bar.ts, line 14 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVLGZ9sNxwExWUY1W:-MzZctjlAdKWWQZ1tCUm:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ADMINS_TAB > ADMIN_TAB
admins-tab > admin-tab
</blockquote></details>

Done.
___
*[cypress/support/components/navigation-bar.ts, line 103 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVTLVCetCbWDbCGXN:-MzZcuhz538TwXzq4ZAD:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L103)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

hasAdminsTab > hasAdminTab
</blockquote></details>

Done.
___
*[cypress/support/components/navigation-bar.ts, line 106 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVUMc30f4KHNi5jTY:-MzZcvJBDUy_qJj57_IZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/cypress/support/components/navigation-bar.ts#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

hasNoAdminsTab > hasNoAdminTab
</blockquote></details>

Done.
___
*[src/styles.scss, line 11 at r2](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-Mz-QP2_5AD1ivTT_6OD:-MzZcH3QCVVh0jjY5Ri-:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/3f872460b00376f73f9dbec6f01c7a9a6fbd4481/src/styles.scss#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be a good idea to add a comment to make this clear. Something like:

```
// Variables overriding Bulma values. These must be set before Bulma is imported.

... variables here, starting with $primary, I guess?

// End: Variables overriding Bulma values
```

</blockquote></details>

Done.
___
*[src/app/navigation-bar/navigation-bar.component.html, line 36 at r4](https://reviewable.io/reviews/saltastroops/web-manager-2021/105#-MzZVa_N9fO0D73aHKUH:-MzZc-5dCLNCo3WEl9GB:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/00c736c8d8b4003abf03d25cedcdb4e19c86bcd7/src/app/navigation-bar/navigation-bar.component.html#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

admins-tab > admin-tab
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 4 of 4 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
