### PR TITLE
Rest of the proposal

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/28)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/28)* status: 11 of 12 files reviewed, 13 unresolved discussions (waiting on @Eb-Zeero)

*[a discussion](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMXbna4aYO3z59OQOa:-MbMXbna4aYO3z59OQOb:bz3a75v) (no related file):*
We should talk about padding in the table cells.

---
___
*[frontend/src/app/nl2br.pipe.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKYPdDYN5iL_4vnX-:-MbMKYPe-ffLgCxoSJIh:b2glcuf) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/nl2br.pipe.ts#L1)):*
> ```XML
> import {Pipe, PipeTransform} from '@angular/core';
> ```

I don't think this file should be at root level.
___
*[frontend/src/app/nl2br.pipe.ts, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKkJG-t4zXlKhirlW:-MbMKkJG-t4zXlKhirlX:b-rjap0z) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/nl2br.pipe.ts#L9)):*
> ```XML
> export class nl2brPipe implements PipeTransform {
>   transform(value: string): string {
>     return value.replace(/\n/g, '<br/>');
> ```

Isn't <br> preferred in HTML5? :-)
___
*[frontend/src/app/types.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMLAV441NdEmHBLJ7B:-MbMLAV441NdEmHBLJ7C:b-90ygex) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L2)):*
> ```XML
> export interface User {
>   name: string;
> ```

Maybe have the given name and family name instead?
___
*[frontend/src/app/types.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKy_dCPOwQVCqdHBD:-MbMKy_dCPOwQVCqdHBE:btign74) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L3)):*
> ```XML
> export interface User {
>   name: string;
>   partner: Partner;
> ```

Why do you need the partner? And what if the user belongs to multiple partners?
___
*[frontend/src/app/types.ts, line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMLdF22ALG-36poD13:-MbMLdF350dXH2ksSTO9:b-vrpis) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L38)):*
> ```XML
>   total_requested_time: number;
>   proprietary_period: number;
>   responsible_salt_astronomer: User;
> ```

Using the User type here might come to bite you, as it may well have properties (such as a user id) which you don't need here.
___
*[frontend/src/app/proposal/details/details.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMMX1v0SRArXfmtG4P:-MbMMX1v0SRArXfmtG4Q:brx15ps) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L1)):*
> ```HTML
> <div class="table">
> ```

"details" is a very generic name. Also, this content is rather part of the general proposal information.

At least parts of this component should be higher up on the page.
___
*[frontend/src/app/proposal/details/details.component.html, line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMWzBSB-CSoE3NHJwC:-MbMWzBSB-CSoE3NHJwD:b-mlxpey) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L28)):*
> ```HTML
>     <div>{{ general_proposal_info.status.status }}</div>
>     <div>{{ general_proposal_info.type }}</div>
>     <div *ngIf="general_proposal_info.target_of_opportunity">
> ```

I guess this could be simplified by binding the src attribute to a dynamic value.
___
*[frontend/src/app/proposal/details/details.component.html, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMO5VoA6ILzpkKauWQ:-MbMO5Vp8Bq8cFLQ2rsi:ba0kqoz) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L48)):*
> ```HTML
>     <div>{{ general_proposal_info.total_requested_time }}</div>
>     <div>
>       {{ general_proposal_info.proprietary_period}} months
> ```

Not aligned properly.
___
*[frontend/src/app/proposal/details/details.component.html, line 58 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMXK7y10aP5uLqBj57:-MbMXK7y10aP5uLqBj58:b-dj8oym) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L58)):*
> ```HTML
>   </div>
>   <div class="download-row row">
>     <div><a>Download XML</a></div>
> ```

Should be in two rows (maybe with a <br>) rather than in two columns.
___
*[frontend/src/app/proposal/details/details.component.html, line 71 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMVfV2Cn331rMm_lP0:-MbMVfV2Cn331rMm_lP1:b3umndr) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L71)):*
> ```HTML
>                class="icon"
>         src="/assets/icons/noun_send email_727617.svg"
> ```

This icon is too small / has too much white space.

The alignment is wrong.

I don't think there should. be two columns.
___
*[frontend/src/app/proposal/details/details.component.html, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMVvAd57YZFCHFwIJi:-MbMVvAd57YZFCHFwIJj:b-rz9ieu) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L75)):*
> ```HTML
>       /> <a>Send email</a>
>     </div>
>       <div class="button is-warning is-small">Edit</div>
> ```

The button should be in a separate row.

Why did you choose the warning colour for it?
___
*[frontend/src/app/proposal/details/details.component.html, line 79 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMNz9nCX6SYCj51o6x:-MbMNz9nCX6SYCj51o6y:bw31qj5) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L79)):*
> ```HTML
> </div>
> 
> <br>
> ```

There should. be no <br> elements.

**Review by hettlage — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/28)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/28)* status: 10 of 14 files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/nl2br.pipe.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKYPdDYN5iL_4vnX-:-Mb_yJWp3qbFWPUGUzea:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/nl2br.pipe.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this file should be at root level.
</blockquote></details>

Done.
___
*[frontend/src/app/nl2br.pipe.ts, line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKkJG-t4zXlKhirlW:-Mb_yJvo0mgp35VDepst:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/nl2br.pipe.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't <br> preferred in HTML5? :-)
</blockquote></details>

Done.
___
*[frontend/src/app/types.ts, line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMKy_dCPOwQVCqdHBD:-Mb_Kis25jcZMwuz-aEn:bbb4ygw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need the partner? And what if the user belongs to multiple partners?
</blockquote></details>

it is need for the poopup for SA
___
*[frontend/src/app/types.ts, line 38 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMLdF22ALG-36poD13:-Mb_LDXX1pwmy1rAnao0:b-2nx97p) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Using the User type here might come to bite you, as it may well have properties (such as a user id) which you don't need here.
</blockquote></details>

then we need a subset of the user to be used
___
*[frontend/src/app/proposal/details/details.component.html, line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMMX1v0SRArXfmtG4P:-Mb_LSk6BKwBAFWoYyMn:b-z57mpw) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"details" is a very generic name. Also, this content is rather part of the general proposal information.

At least parts of this component should be higher up on the page.
</blockquote></details>

yes the tables needs to be rearranged waiting for all to be aproved
___
*[frontend/src/app/proposal/details/details.component.html, line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMO5VoA6ILzpkKauWQ:-Mb_PBTx5iqtVuqrN8qy:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Not aligned properly.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/details/details.component.html, line 58 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMXK7y10aP5uLqBj57:-Mbfyq803NbO6Cxlmq-S:b-896fix) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L58)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be in two rows (maybe with a <br>) rather than in two columns.
</blockquote></details>

Done.
___
*[frontend/src/app/proposal/details/details.component.html, line 71 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMVfV2Cn331rMm_lP0:-MbfxqDeATdmyD4KBQbV:bgreq8h) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This icon is too small / has too much white space.

The alignment is wrong.

I don't think there should. be two columns.
</blockquote></details>

not applicable
___
*[frontend/src/app/proposal/details/details.component.html, line 75 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMVvAd57YZFCHFwIJi:-MbfxtlG52szUCIP5C6M:b-7ql1td) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The button should be in a separate row.

Why did you choose the warning colour for it?
</blockquote></details>

fixed
___
*[frontend/src/app/proposal/details/details.component.html, line 79 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-MbMNz9nCX6SYCj51o6x:-MbfxvjcEy5o_pOpMk5I:bmrszk2) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/proposal/details/details.component.html#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should. be no <br> elements.
</blockquote></details>

yes removed

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager-2021/28)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[frontend/src/app/types.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager-2021/28#-Mbg38wt5SsLZHG9WKCt:-Mbg38wt5SsLZHG9WKCu:b-lu1mzm) ([raw file](https://github.com/saltastroops/web-manager-2021/blob/ab09249f769b036e0b5127cdc8476776bf7aaf4c/frontend/src/app/types.ts#L2)):*
> ```XML
> export interface User {
>   name: string;
> ```

Should be given_name and family_name.

BUT: This is ultimately an API decision, so it might be changed later.

**Pull request merged**
